# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
use_frameworks!

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  
  pod 'LiveKit', :path => '../'
  # Pods for Example

end
