/*
 * Copyright 2026 LiveKit
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import Foundation
import Testing

/// Deep conformance: a generated, fully-populated exemplar of every facade
/// message (and every oneof variant separately) is built through both
/// implementations. See Generated/ConformanceExemplars.swift — regenerated by
/// `make proto`, so coverage tracks the protos mechanically.
@Suite("generated exemplar conformance")
struct ExemplarConformanceTests {
    @Test("every message encodes byte-identically to the oracle", arguments: conformanceExemplars)
    func fullMessage(_ exemplar: ConformanceExemplar) throws {
        let facadeBytes = try exemplar.facade()
        let oracleBytes = try exemplar.oracle()
        #expect(facadeBytes == oracleBytes)

        // decode → encode through the facade must not lose or reorder fields
        let reencoded = try exemplar.reencode(oracleBytes)
        #expect(reencoded == oracleBytes)
    }

    @Test("every oneof variant round-trips identically", arguments: oneofVariantExemplars)
    func oneofVariant(_ exemplar: ConformanceExemplar) throws {
        let facadeBytes = try exemplar.facade()
        let oracleBytes = try exemplar.oracle()
        #expect(facadeBytes == oracleBytes)

        let reencoded = try exemplar.reencode(oracleBytes)
        #expect(reencoded == oracleBytes)
    }
}
