/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "livekit_rtc.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(livekit_SignalRequest, livekit_SignalRequest, AUTO)


PB_BIND(livekit_SignalResponse, livekit_SignalResponse, AUTO)


PB_BIND(livekit_SimulcastCodec, livekit_SimulcastCodec, AUTO)


PB_BIND(livekit_AddTrackRequest, livekit_AddTrackRequest, AUTO)


PB_BIND(livekit_PublishDataTrackRequest, livekit_PublishDataTrackRequest, AUTO)


PB_BIND(livekit_PublishDataTrackResponse, livekit_PublishDataTrackResponse, AUTO)


PB_BIND(livekit_UnpublishDataTrackRequest, livekit_UnpublishDataTrackRequest, AUTO)


PB_BIND(livekit_UnpublishDataTrackResponse, livekit_UnpublishDataTrackResponse, AUTO)


PB_BIND(livekit_DataTrackSubscriberHandles, livekit_DataTrackSubscriberHandles, AUTO)


PB_BIND(livekit_DataTrackSubscriberHandles_PublishedDataTrack, livekit_DataTrackSubscriberHandles_PublishedDataTrack, AUTO)


PB_BIND(livekit_DataTrackSubscriberHandles_SubHandlesEntry, livekit_DataTrackSubscriberHandles_SubHandlesEntry, AUTO)


PB_BIND(livekit_TrickleRequest, livekit_TrickleRequest, AUTO)


PB_BIND(livekit_MuteTrackRequest, livekit_MuteTrackRequest, AUTO)


PB_BIND(livekit_JoinResponse, livekit_JoinResponse, AUTO)


PB_BIND(livekit_ReconnectResponse, livekit_ReconnectResponse, AUTO)


PB_BIND(livekit_TrackPublishedResponse, livekit_TrackPublishedResponse, AUTO)


PB_BIND(livekit_TrackUnpublishedResponse, livekit_TrackUnpublishedResponse, AUTO)


PB_BIND(livekit_SessionDescription, livekit_SessionDescription, AUTO)


PB_BIND(livekit_SessionDescription_MidToTrackIdEntry, livekit_SessionDescription_MidToTrackIdEntry, AUTO)


PB_BIND(livekit_ParticipantUpdate, livekit_ParticipantUpdate, AUTO)


PB_BIND(livekit_UpdateSubscription, livekit_UpdateSubscription, AUTO)


PB_BIND(livekit_UpdateDataSubscription, livekit_UpdateDataSubscription, AUTO)


PB_BIND(livekit_UpdateDataSubscription_Update, livekit_UpdateDataSubscription_Update, AUTO)


PB_BIND(livekit_StoreDataBlobRequest, livekit_StoreDataBlobRequest, AUTO)


PB_BIND(livekit_StoreDataBlobResponse, livekit_StoreDataBlobResponse, AUTO)


PB_BIND(livekit_GetDataBlobRequest, livekit_GetDataBlobRequest, AUTO)


PB_BIND(livekit_GetDataBlobResponse, livekit_GetDataBlobResponse, AUTO)


PB_BIND(livekit_UpdateTrackSettings, livekit_UpdateTrackSettings, AUTO)


PB_BIND(livekit_UpdateLocalAudioTrack, livekit_UpdateLocalAudioTrack, AUTO)


PB_BIND(livekit_UpdateLocalVideoTrack, livekit_UpdateLocalVideoTrack, AUTO)


PB_BIND(livekit_LeaveRequest, livekit_LeaveRequest, AUTO)


PB_BIND(livekit_UpdateVideoLayers, livekit_UpdateVideoLayers, AUTO)


PB_BIND(livekit_UpdateParticipantMetadata, livekit_UpdateParticipantMetadata, AUTO)


PB_BIND(livekit_UpdateParticipantMetadata_AttributesEntry, livekit_UpdateParticipantMetadata_AttributesEntry, AUTO)


PB_BIND(livekit_ICEServer, livekit_ICEServer, AUTO)


PB_BIND(livekit_SpeakersChanged, livekit_SpeakersChanged, AUTO)


PB_BIND(livekit_RoomUpdate, livekit_RoomUpdate, AUTO)


PB_BIND(livekit_ConnectionQualityInfo, livekit_ConnectionQualityInfo, AUTO)


PB_BIND(livekit_ConnectionQualityUpdate, livekit_ConnectionQualityUpdate, AUTO)


PB_BIND(livekit_StreamStateInfo, livekit_StreamStateInfo, AUTO)


PB_BIND(livekit_StreamStateUpdate, livekit_StreamStateUpdate, AUTO)


PB_BIND(livekit_SubscribedQuality, livekit_SubscribedQuality, AUTO)


PB_BIND(livekit_SubscribedCodec, livekit_SubscribedCodec, AUTO)


PB_BIND(livekit_SubscribedQualityUpdate, livekit_SubscribedQualityUpdate, AUTO)


PB_BIND(livekit_SubscribedAudioCodecUpdate, livekit_SubscribedAudioCodecUpdate, AUTO)


PB_BIND(livekit_TrackPermission, livekit_TrackPermission, AUTO)


PB_BIND(livekit_SubscriptionPermission, livekit_SubscriptionPermission, AUTO)


PB_BIND(livekit_SubscriptionPermissionUpdate, livekit_SubscriptionPermissionUpdate, AUTO)


PB_BIND(livekit_RoomMovedResponse, livekit_RoomMovedResponse, AUTO)


PB_BIND(livekit_SyncState, livekit_SyncState, AUTO)


PB_BIND(livekit_DataChannelReceiveState, livekit_DataChannelReceiveState, AUTO)


PB_BIND(livekit_DataChannelInfo, livekit_DataChannelInfo, AUTO)


PB_BIND(livekit_SimulateScenario, livekit_SimulateScenario, AUTO)


PB_BIND(livekit_Ping, livekit_Ping, AUTO)


PB_BIND(livekit_Pong, livekit_Pong, AUTO)


PB_BIND(livekit_RegionSettings, livekit_RegionSettings, AUTO)


PB_BIND(livekit_RegionInfo, livekit_RegionInfo, AUTO)


PB_BIND(livekit_SubscriptionResponse, livekit_SubscriptionResponse, AUTO)


PB_BIND(livekit_RequestResponse, livekit_RequestResponse, AUTO)


PB_BIND(livekit_TrackSubscribed, livekit_TrackSubscribed, AUTO)


PB_BIND(livekit_ConnectionSettings, livekit_ConnectionSettings, AUTO)


PB_BIND(livekit_JoinRequest, livekit_JoinRequest, AUTO)


PB_BIND(livekit_JoinRequest_ParticipantAttributesEntry, livekit_JoinRequest_ParticipantAttributesEntry, AUTO)


PB_BIND(livekit_WrappedJoinRequest, livekit_WrappedJoinRequest, AUTO)


PB_BIND(livekit_MediaSectionsRequirement, livekit_MediaSectionsRequirement, AUTO)















