/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "livekit_metrics.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(livekit_MetricsBatch, livekit_MetricsBatch, AUTO)


PB_BIND(livekit_TimeSeriesMetric, livekit_TimeSeriesMetric, AUTO)


PB_BIND(livekit_MetricSample, livekit_MetricSample, AUTO)


PB_BIND(livekit_EventMetric, livekit_EventMetric, AUTO)


PB_BIND(livekit_MetricsRecordingHeader, livekit_MetricsRecordingHeader, AUTO)


PB_BIND(livekit_MetricsRecordingHeader_RoomTagsEntry, livekit_MetricsRecordingHeader_RoomTagsEntry, AUTO)





