/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LOGGER_LOGGER_OPTIONS_PB_H_INCLUDED
#define PB_LOGGER_LOGGER_OPTIONS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Extensions */
/* Extension field logger_redact was skipped because only "optional"
   type of extension fields is currently supported. */
/* Extension field logger_redact_format was skipped because only "optional"
   type of extension fields is currently supported. */
/* Extension field logger_name was skipped because only "optional"
   type of extension fields is currently supported. */

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
