/*
 * Copyright 2026 LiveKit
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Runtime for the nanopb-backed protobuf facades generated by
// scripts/generate-swift-protos.swift.
//
// Messages are immutable value types. A `NanopbBox` owns one nanopb-allocated
// C struct; copying a message is a refcount bump and can never deep-copy,
// because nothing can mutate a message once it exists. Mutation lives on a
// per-message noncopyable `Builder` that owns storage nothing else can reach,
// so populating a message needs no uniqueness check at all.
//
// Messages stay copyable (they hold a copyable box), so arrays, dictionaries,
// `Equatable` state and `Sendable` closures work unchanged; only the builder is
// `~Copyable`, and it never needs to enter a collection.
//
// The wire format lives entirely in nanopb's C tables, so this file is a fixed
// cost that does not grow with the number of messages — SwiftProtobuf's runtime
// links ~1.1 MB no matter how few messages you use.

// Single-module builds compile these sources into the product directly:
// CocoaPods surfaces the C declarations through the umbrella header, while the
// prebuilt xcframework resolves CLiveKitProto via its modulemap (package import
// so `package` declarations may expose C types without entering the public
// .swiftinterface).
#if LK_XCFRAMEWORK
package import CLiveKitProto
#elseif !COCOAPODS
import CLiveKitProto
#endif
import Foundation
import os

// MARK: - Errors

private let nanopbLog = OSLog(subsystem: "io.livekit.nanopb", category: "runtime")

/// Reports a failure on a path that cannot throw (builder setters, copies).
/// These only fail on allocation exhaustion or a descriptor bug; the callers
/// degrade to the least-damaging outcome instead of crashing, and this makes
/// the degradation observable (Console, sysdiagnose).
package func nanopbReportFailure(_ operation: StaticString, _ error: Error) {
    os_log(.fault, log: nanopbLog, "%{public}@ failed: %{public}@", "\(operation)", "\(error)")
}

package enum NanopbError: Error, CustomStringConvertible {
    case decodeFailed(String)
    case encodeFailed(String)
    case allocationFailed

    package var description: String {
        switch self {
        case let .decodeFailed(message): "nanopb decode failed: \(message)"
        case let .encodeFailed(message): "nanopb encode failed: \(message)"
        case .allocationFailed: "nanopb allocation failed"
        }
    }
}

// MARK: - Storage box

/// Non-generic base so `_owner` has a concrete class type. Through an
/// `AnyObject` existential `isKnownUniquelyReferenced` reports false in
/// unoptimised builds, which would silently make `modifying` always copy.
package class NanopbAnyBox: @unchecked Sendable {
    /// The owned struct's address, readable without a generic downcast — a
    /// downcast would hold a second reference across the uniqueness check in
    /// `modifying`, which is exactly what that check must not see.
    package let rawPointer: UnsafeMutableRawPointer

    package init(rawPointer: UnsafeMutableRawPointer) {
        self.rawPointer = rawPointer
    }
}

/// Owns one nanopb C struct in a malloc'd, address-stable allocation;
/// `pb_release` frees its dynamic fields on deinit.
///
/// `@unchecked Sendable` because storage a message value can reach is never
/// mutated: a message exposes no setters, and the `Builder` that populated it
/// was consumed by `build()`. Child views retain their parent's box, so a
/// parent going out of scope cannot free storage a live view points into.
package final class NanopbBox<Storage>: NanopbAnyBox, @unchecked Sendable {
    package let pointer: UnsafeMutablePointer<Storage>
    let descriptor: pb_msgdesc_t

    package init(zero: Storage, descriptor: pb_msgdesc_t) {
        // SAFETY: the allocation is address-stable for the box's lifetime,
        // which is what lets views point into it; `deinit` is the only place
        // it is torn down, and it pairs every step taken here.
        pointer = .allocate(capacity: 1)
        pointer.initialize(to: zero)
        self.descriptor = descriptor
        super.init(rawPointer: UnsafeMutableRawPointer(pointer))
    }

    deinit {
        // SAFETY: `lk_pb_release` frees the dynamic fields and nulls them, so
        // a double release is harmless — `pb_decode` may already have released
        // partial state after a failed decode into this same storage.
        var descriptor = descriptor
        lk_pb_release(&descriptor, UnsafeMutableRawPointer(pointer))
        pointer.deinitialize(count: 1)
        pointer.deallocate()
    }
}

// MARK: - Builder

/// The only way to mutate a message. One generic builder serves every message
/// type; the generated code adds just the field setters in a constrained
/// extension (`extension NanopbBuilder where S == livekit_Room`), which is
/// what SE-0427 noncopyable generics makes possible.
///
/// `~Copyable` means the compiler proves there is never a second live handle
/// to this storage, so no uniqueness check is needed, and `build()` consumes
/// the builder so nothing can write to storage after it is published.
///
/// `_pointer` is *stored*, not computed off `_box`: as a computed property it
/// crashes the Swift 6.1 SIL verifier (fine from 6.2), and 6.1 is the floor.
package struct NanopbBuilder<S: NanopbStorage>: ~Copyable {
    package let _box: NanopbBox<S>
    package let _pointer: UnsafeMutablePointer<S>

    package init() {
        self.init(_adopting: NanopbBox(zero: S(), descriptor: S.descriptor))
    }

    package init(_adopting box: NanopbBox<S>) {
        _box = box
        _pointer = box.pointer
    }

    package consuming func build() -> NanopbMsg<S> { NanopbMsg(_owning: _box) }
}

// MARK: - Storage

/// What the generic message needs to know about one schema type.
///
/// The generated code's entire per-message contribution is a conformance to
/// this plus one accessor per field, so the schema adds no Swift *types* —
/// which is what actually costs binary size, since a nominal type's metadata
/// and conformance records survive dead-stripping even when unreferenced.
///
/// Imported C structs synthesise `init()`, so conformances get it for free.
///
/// `_emptyBox` lives here rather than on `NanopbMsg` because Swift forbids
/// stored statics in a generic type, and a computed `Self()` would allocate on
/// every read of an absent submessage.
package protocol NanopbStorage {
    init()
    /// nanopb's field table for this struct.
    static var descriptor: pb_msgdesc_t { get }
    /// Shared, permanently-empty storage handed out for absent submessages.
    static var _emptyBox: NanopbBox<Self> { get }
    /// Rendering for logs.
    ///
    /// Messages share one `CustomStringConvertible` conformance, so there is
    /// exactly one witness and every dynamic use — interpolation,
    /// `String(describing:)` — lands on it. A member on a constrained
    /// extension would only be reachable where the concrete type is known
    /// statically, which is not where logging happens. Per-message detail
    /// therefore has to hang off the storage type, which is what varies.
    static func _describe(_ message: NanopbMsg<Self>) -> String
}

package extension NanopbStorage {
    /// Most messages are never logged individually; the type name is enough to
    /// identify one inside a larger log line.
    static func _describe(_: NanopbMsg<Self>) -> String { "\(Self.self)" }
}

// MARK: - Message

/// An immutable protobuf message whose storage and wire format are nanopb's.
///
/// One type serves the whole schema: `Livekit_Room` is a typealias for
/// `NanopbMsg<livekit_Room>`, and the generated code adds field accessors in a
/// constrained extension. A value is in one of two states:
///
/// - **Owning**: `_owner` is its own `NanopbBox`; `box.pointer == _pointer`.
/// - **View**: `_pointer` aims at a nested C struct *inside another message's
///   allocation*, and `_owner` is that parent's box. Submessage and repeated
///   getters return views — reads are zero-copy pointer reads.
///
/// Messages have no setters: mutation goes through the noncopyable `Builder`,
/// and `with` / `modifying` are the only ways to produce a populated value.
package struct NanopbMsg<S: NanopbStorage>: Equatable, Hashable, @unchecked Sendable {
    /// Keeps `_pointer`'s allocation alive: this value's own box, or the box
    /// of the message this value is a view into.
    package var _owner: NanopbAnyBox
    package var _pointer: UnsafeMutablePointer<S>

    package init() {
        self.init(_owning: NanopbBox(zero: S(), descriptor: S.descriptor))
    }

    package init(_owning box: NanopbBox<S>) {
        _owner = box
        _pointer = box.pointer
    }

    /// Zero-copy view into `owner`'s storage.
    package init(_sharing pointer: UnsafeMutablePointer<S>, owner: NanopbAnyBox) {
        _owner = owner
        _pointer = pointer
    }

    /// Shared value returned when a submessage field is absent. Safe to share
    /// because messages are immutable; `modifying` sees the shared reference,
    /// so it copies rather than writing through it.
    package static var _empty: Self { Self(_owning: S._emptyBox) }

    /// Forwarded so generated accessors can name the descriptor through the
    /// message type, as they did when every message was a nominal type.
    package static var descriptor: pb_msgdesc_t { S.descriptor }

    package typealias Builder = NanopbBuilder<S>

    package static func with(_ populate: (inout Builder) throws -> Void) rethrows -> Self {
        var builder = Builder()
        try populate(&builder)
        return builder.build()
    }

    /// This message with `populate` applied. `consuming` ends the caller's
    /// ownership, so when nothing else holds the storage the mutation happens
    /// in place; otherwise it copies once for the whole batch, not per field.
    package consuming func modifying(_ populate: (inout Builder) throws -> Void) rethrows -> Self {
        if _ownsItsStorage, isKnownUniquelyReferenced(&_owner) {
            var builder = Builder(_adopting: unsafeDowncast(_owner, to: NanopbBox<S>.self))
            try populate(&builder)
            return builder.build()
        }
        var builder = Builder()
        lkOverwrite(builder._pointer, with: self)
        try populate(&builder)
        return builder.build()
    }

    /// A value that owns its own storage, copying out of its parent only if
    /// this one is a view — the same contract as Rust's `Cow::into_owned`.
    ///
    /// Submessage and repeated getters return zero-copy *views* whose `_owner`
    /// is the box of the whole decoded message, so storing a view long-term
    /// keeps that entire allocation alive (as `Substring` does to its
    /// `String`). Call this when promoting a decoded sub-message into
    /// long-lived state. Owning values cost nothing.
    package func owned() -> Self {
        if _ownsItsStorage { return self }
        return lkMessage(copying: _pointer)
    }

    /// True when `_owner` is this value's own box rather than a parent's,
    /// tested without retaining the box.
    package var _ownsItsStorage: Bool {
        // SAFETY: compares addresses only. A `NanopbBox<S>` downcast would
        // hold a second reference across `modifying`'s uniqueness check and
        // make it always fail.
        _owner.rawPointer == UnsafeMutableRawPointer(_pointer)
    }

    // MARK: Wire format

    package init(serializedBytes bytes: some Collection<UInt8>) throws(NanopbError) {
        self.init()
        let array = Array(bytes)
        // see `nanopbEncodedBytes` on why the error is captured rather than
        // propagated straight through the stdlib's untyped `rethrows`
        var failure: NanopbError?
        array.withUnsafeBytes { buffer in
            do throws(NanopbError) {
                try nanopbDecode(into: _pointer, S.descriptor, buffer)
            } catch {
                failure = error
            }
        }
        if let failure { throw failure }
    }

    package init(serializedData data: Data) throws(NanopbError) {
        try self.init(serializedBytes: data)
    }

    package func serializedBytes() throws(NanopbError) -> [UInt8] {
        try nanopbEncodedBytes(_pointer, S.descriptor)
    }

    package func serializedData() throws(NanopbError) -> Data {
        try Data(serializedBytes())
    }

    // MARK: Equatable / Hashable

    //
    // Canonical-bytes comparison. nanopb encodes deterministically, except that
    // map fields preserve entry *order* — equal maps built in different orders
    // compare unequal. The SDK uses equality for change detection, where a
    // false "changed" is benign.

    package static func == (lhs: Self, rhs: Self) -> Bool {
        if lhs._pointer == rhs._pointer { return true }
        return (try? lhs.serializedBytes()) == (try? rhs.serializedBytes())
    }

    package func hash(into hasher: inout Hasher) {
        hasher.combine((try? serializedBytes()) ?? [])
    }
}

/// A protobuf enum. proto3 enums are open, so an unknown wire value is a
/// perfectly good value rather than a special case — hence a non-failable
/// `init(rawValue:)` and no `UNRECOGNIZED` payload.
package protocol NanopbEnum: RawRepresentable, Hashable, Sendable where RawValue == Int {
    init()
    /// Non-failable on purpose, and not redundant with `RawRepresentable`'s
    /// `init?`: it is what forces every conformer to accept a value this build
    /// has never heard of, so an unknown enum arriving on the wire survives a
    /// decode/encode round trip instead of collapsing to the zero case.
    /// Generic call sites still resolve to `init?`, whose failure branch is
    /// therefore unreachable.
    init(rawValue: Int)
}
