/*
 * Copyright 2026 LiveKit
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Runtime for the nanopb-backed protobuf facades generated by
// scripts/generate-facades.swift.
//
// Messages are copy-on-write value types that clone protoc-gen-swift's API, so
// existing call sites (arrays, Equatable state, Sendable delegate closures)
// keep working. A `NanopbBox` owns one nanopb-allocated C struct; copies of a
// message are refcount bumps, and a deep copy (an encode/decode round trip)
// happens only when a *shared* value is mutated — rare in practice, since
// messages are typically built-encode-drop or decode-read-drop.
//
// The wire format lives entirely in nanopb's C tables, so this file is a fixed
// cost that does not grow with the number of messages — SwiftProtobuf's runtime
// links ~1.1 MB no matter how few messages you use.
//
// Zero-copy `withXBytes { }` readers are emitted alongside for hot paths.

// CocoaPods compiles all of Sources into the single LiveKitClient module;
// there the C declarations arrive through the umbrella header instead.
#if !COCOAPODS
import CLiveKitProto
#endif
import Foundation

// MARK: - Errors

public enum NanopbError: Error, CustomStringConvertible {
    case decodeFailed(String)
    case encodeFailed(String)
    case allocationFailed

    public var description: String {
        switch self {
        case let .decodeFailed(message): "nanopb decode failed: \(message)"
        case let .encodeFailed(message): "nanopb encode failed: \(message)"
        case .allocationFailed: "nanopb allocation failed"
        }
    }
}

// MARK: - Storage box

/// Owns one nanopb C struct in a malloc'd, address-stable allocation;
/// `pb_release` frees its dynamic fields on deinit.
///
/// `@unchecked Sendable` under the copy-on-write invariant (same justification
/// as `Array`): storage reachable from more than one message value is never
/// mutated — `_ensureUnique()` detaches first. Child views retain their
/// parent's box, so a parent that copies itself away cannot free storage a
/// live view still points into.
public final class NanopbBox<Storage>: @unchecked Sendable {
    public let pointer: UnsafeMutablePointer<Storage>
    @usableFromInline let descriptor: pb_msgdesc_t

    public init(zero: Storage, descriptor: pb_msgdesc_t) {
        pointer = .allocate(capacity: 1)
        pointer.initialize(to: zero)
        self.descriptor = descriptor
    }

    deinit {
        var descriptor = descriptor
        pb_release(&descriptor, UnsafeMutableRawPointer(pointer))
        pointer.deinitialize(count: 1)
        pointer.deallocate()
    }
}

// MARK: - Protocols

/// A protobuf message whose storage and wire format are nanopb's.
///
/// A value either owns its allocation (`_owner` is its own box) or is a *view*
/// sharing a parent message's box, pointing directly at the nested C struct.
/// Reads are pointer reads either way; the first mutation of any non-uniquely
/// owned value detaches it via an encode/decode round trip of its subtree.
public protocol NanopbMessage: Equatable, Hashable, Sendable {
    associatedtype Storage

    /// nanopb's field table for `Storage`.
    static var descriptor: pb_msgdesc_t { get }
    /// A zeroed `Storage`, i.e. nanopb's `<T>_init_zero`.
    static var zero: Storage { get }

    /// Keeps `_pointer`'s allocation alive: this value's own box, or the box
    /// of the message this value is a view into.
    var _owner: AnyObject { get set }
    var _pointer: UnsafeMutablePointer<Storage> { get set }

    init()
    /// A view into storage owned by `owner` — zero-copy.
    init(_sharing pointer: UnsafeMutablePointer<Storage>, owner: AnyObject)
}

public extension NanopbMessage {
    /// Copy-on-write guard: call before any mutation. Detaches this value —
    /// copying only its own subtree — when its storage is shared with any
    /// other value (a copy, or the parent/child of a view).
    mutating func _ensureUnique() {
        if !isKnownUniquelyReferenced(&_owner) {
            let fresh = NanopbBox<Storage>(zero: Self.zero, descriptor: Self.descriptor)
            if let bytes = try? nanopbEncodedBytes(_pointer, Self.descriptor) {
                try? bytes.withUnsafeBytes {
                    try? nanopbDecode(into: fresh.pointer, Self.descriptor, $0)
                }
            }
            _owner = fresh
            _pointer = fresh.pointer
        }
    }

    /// protoc-gen-swift's builder.
    static func with(_ populator: (inout Self) throws -> Void) rethrows -> Self {
        var message = Self()
        try populator(&message)
        return message
    }

    // MARK: Wire format

    init(serializedBytes bytes: some Collection<UInt8>) throws {
        self.init()
        let array = Array(bytes)
        try array.withUnsafeBytes { try nanopbDecode(into: _pointer, Self.descriptor, $0) }
    }

    init(serializedData data: Data) throws {
        try self.init(serializedBytes: data)
    }

    func serializedBytes() throws -> [UInt8] {
        try nanopbEncodedBytes(_pointer, Self.descriptor)
    }

    func serializedData() throws -> Data {
        try Data(serializedBytes())
    }

    /// Encode into scratch space and hand it to `body` — nothing heap-allocated.
    func withEncodedBytes<R>(_ body: (UnsafeRawBufferPointer) throws -> R) throws -> R {
        let size = try nanopbEncodedSize(_pointer, Self.descriptor)
        return try withUnsafeTemporaryAllocation(byteCount: size, alignment: 1) { buffer in
            let written = try nanopbEncode(_pointer, Self.descriptor, into: buffer)
            return try body(UnsafeRawBufferPointer(rebasing: buffer[..<written]))
        }
    }

    // MARK: Equatable / Hashable

    //
    // Canonical-bytes comparison. nanopb encodes deterministically, except that
    // map fields preserve entry *order* — equal maps built in different orders
    // compare unequal. The SDK uses equality for change detection, where a
    // false "changed" is benign.

    static func == (lhs: Self, rhs: Self) -> Bool {
        if lhs._pointer == rhs._pointer { return true }
        return (try? lhs.serializedBytes()) == (try? rhs.serializedBytes())
    }

    func hash(into hasher: inout Hasher) {
        hasher.combine((try? serializedBytes()) ?? [])
    }
}

/// A protobuf enum. Mirrors SwiftProtobuf's open-enum shape (`UNRECOGNIZED`).
public protocol NanopbEnum: RawRepresentable, Hashable, Sendable where RawValue == Int {
    init()
}

// MARK: - Wire-format primitives

@inlinable
public func nanopbDecode(
    into pointer: UnsafeMutablePointer<some Any>,
    _ descriptor: pb_msgdesc_t,
    _ bytes: UnsafeRawBufferPointer,
) throws {
    var descriptor = descriptor
    var stream = pb_istream_from_buffer(
        bytes.baseAddress?.assumingMemoryBound(to: UInt8.self), bytes.count,
    )
    guard pb_decode(&stream, &descriptor, UnsafeMutableRawPointer(pointer)) else {
        throw NanopbError.decodeFailed(stream.errmsg.map { String(cString: $0) } ?? "unknown")
    }
}

@inlinable
public func nanopbEncodedSize(
    _ pointer: UnsafePointer<some Any>, _ descriptor: pb_msgdesc_t,
) throws -> Int {
    var descriptor = descriptor
    var size = 0
    guard pb_get_encoded_size(&size, &descriptor, UnsafeRawPointer(pointer)) else {
        throw NanopbError.encodeFailed("size")
    }
    return size
}

@inlinable
public func nanopbEncode(
    _ pointer: UnsafePointer<some Any>,
    _ descriptor: pb_msgdesc_t,
    into buffer: UnsafeMutableRawBufferPointer,
) throws -> Int {
    var descriptor = descriptor
    var stream = pb_ostream_from_buffer(
        buffer.baseAddress?.assumingMemoryBound(to: UInt8.self), buffer.count,
    )
    guard pb_encode(&stream, &descriptor, UnsafeRawPointer(pointer)) else {
        throw NanopbError.encodeFailed("encode")
    }
    return stream.bytes_written
}

@inlinable
public func nanopbEncodedBytes(
    _ pointer: UnsafePointer<some Any>, _ descriptor: pb_msgdesc_t,
) throws -> [UInt8] {
    let size = try nanopbEncodedSize(pointer, descriptor)
    var out = [UInt8](repeating: 0, count: size)
    let written = try out.withUnsafeMutableBytes { try nanopbEncode(pointer, descriptor, into: $0) }
    if written != size { out.removeLast(size - written) }
    return out
}
