/*
 * Copyright 2026 LiveKit
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Runtime for the nanopb-backed protobuf facades generated by
// scripts/generate-swift-protos.swift.
//
// Messages are immutable value types. A `NanopbBox` owns one nanopb-allocated
// C struct; copying a message is a refcount bump and can never deep-copy,
// because nothing can mutate a message once it exists. Mutation lives on a
// per-message noncopyable `Builder` that owns storage nothing else can reach,
// so populating a message needs no uniqueness check at all.
//
// Messages stay copyable (they hold a copyable box), so arrays, dictionaries,
// `Equatable` state and `Sendable` closures work unchanged; only the builder is
// `~Copyable`, and it never needs to enter a collection.
//
// The wire format lives entirely in nanopb's C tables, so this file is a fixed
// cost that does not grow with the number of messages — SwiftProtobuf's runtime
// links ~1.1 MB no matter how few messages you use.
//
// Zero-copy `withXBytes { }` readers are emitted alongside for hot paths.

// Single-module builds compile these sources into the product directly:
// CocoaPods surfaces the C declarations through the umbrella header, while the
// prebuilt xcframework resolves CLiveKitProto via its modulemap (package import
// so `package` declarations may expose C types without entering the public
// .swiftinterface).
#if LK_XCFRAMEWORK
package import CLiveKitProto
#elseif !COCOAPODS
import CLiveKitProto
#endif
import Foundation
import os

// MARK: - Errors

private let nanopbLog = OSLog(subsystem: "io.livekit.nanopb", category: "runtime")

/// Reports a failure on a path that cannot throw (builder setters, copies).
/// These only fail on allocation exhaustion or a descriptor bug; the callers
/// degrade to the least-damaging outcome instead of crashing, and this makes
/// the degradation observable (Console, sysdiagnose).
package func nanopbReportFailure(_ operation: StaticString, _ error: Error) {
    os_log(.fault, log: nanopbLog, "%{public}@ failed: %{public}@", "\(operation)", "\(error)")
}

package enum NanopbError: Error, CustomStringConvertible {
    case decodeFailed(String)
    case encodeFailed(String)
    case allocationFailed

    package var description: String {
        switch self {
        case let .decodeFailed(message): "nanopb decode failed: \(message)"
        case let .encodeFailed(message): "nanopb encode failed: \(message)"
        case .allocationFailed: "nanopb allocation failed"
        }
    }
}

// MARK: - Storage box

/// Non-generic base so `_owner` has a concrete class type. Through an
/// `AnyObject` existential `isKnownUniquelyReferenced` reports false in
/// unoptimised builds, which would silently make `modifying` always copy.
package class NanopbAnyBox: @unchecked Sendable {
    /// The owned struct's address, readable without a generic downcast — a
    /// downcast would hold a second reference across the uniqueness check in
    /// `modifying`, which is exactly what that check must not see.
    package let rawPointer: UnsafeMutableRawPointer

    package init(rawPointer: UnsafeMutableRawPointer) {
        self.rawPointer = rawPointer
    }
}

/// Owns one nanopb C struct in a malloc'd, address-stable allocation;
/// `pb_release` frees its dynamic fields on deinit.
///
/// `@unchecked Sendable` because storage a message value can reach is never
/// mutated: a message exposes no setters, and the `Builder` that populated it
/// was consumed by `build()`. Child views retain their parent's box, so a
/// parent going out of scope cannot free storage a live view points into.
package final class NanopbBox<Storage>: NanopbAnyBox, @unchecked Sendable {
    package let pointer: UnsafeMutablePointer<Storage>
    let descriptor: pb_msgdesc_t

    package init(zero: Storage, descriptor: pb_msgdesc_t) {
        // SAFETY: the allocation is address-stable for the box's lifetime,
        // which is what lets views point into it; `deinit` is the only place
        // it is torn down, and it pairs every step taken here.
        pointer = .allocate(capacity: 1)
        pointer.initialize(to: zero)
        self.descriptor = descriptor
        super.init(rawPointer: UnsafeMutableRawPointer(pointer))
    }

    deinit {
        // SAFETY: `lk_pb_release` frees the dynamic fields and nulls them, so
        // a double release is harmless — `pb_decode` may already have released
        // partial state after a failed decode into this same storage.
        var descriptor = descriptor
        lk_pb_release(&descriptor, UnsafeMutableRawPointer(pointer))
        pointer.deinitialize(count: 1)
        pointer.deallocate()
    }
}

// MARK: - Protocols

/// An immutable protobuf message whose storage and wire format are nanopb's.
///
/// A value either owns its allocation (`_owner` is its own box) or is a *view*
/// sharing a parent message's box, pointing directly at the nested C struct.
/// Reads are pointer reads either way. Messages have no setters: each generated
/// type carries a noncopyable `Builder` that owns fresh storage, and `with` /
/// `modifying` are the only ways to produce a populated value.
package protocol NanopbMessage: Equatable, Hashable, Sendable {
    associatedtype Storage

    /// nanopb's field table for `Storage`.
    static var descriptor: pb_msgdesc_t { get }
    /// A zeroed `Storage`, i.e. nanopb's `<T>_init_zero`.
    static var zero: Storage { get }

    /// Keeps `_pointer`'s allocation alive: this value's own box, or the box
    /// of the message this value is a view into.
    var _owner: NanopbAnyBox { get set }
    var _pointer: UnsafeMutablePointer<Storage> { get set }

    init()
    /// Shared empty value handed out for absent submessage fields.
    static var _empty: Self { get }
    /// A view into storage owned by `owner` — zero-copy.
    init(_sharing pointer: UnsafeMutablePointer<Storage>, owner: NanopbAnyBox)
}

package extension NanopbMessage {
    /// A value that owns its own storage, copying out of its parent only if
    /// this one is a view — the same contract as Rust's `Cow::into_owned`.
    ///
    /// Submessage and repeated getters return zero-copy *views* whose `_owner`
    /// is the box of the whole decoded message, so storing a view long-term
    /// keeps that entire allocation alive (as `Substring` does to its
    /// `String`). Call this when promoting a decoded sub-message into
    /// long-lived state. Values that already own their storage cost nothing.
    func owned() -> Self {
        if _ownsItsStorage { return self }
        return lkMessage(copying: _pointer)
    }

    /// True when `_owner` is this value's own box rather than a parent's,
    /// tested without retaining the box.
    var _ownsItsStorage: Bool {
        // SAFETY: compares addresses only. A `NanopbBox<Storage>` downcast
        // would hold a second reference across `modifying`'s uniqueness
        // check and make it always fail.
        _owner.rawPointer == UnsafeMutableRawPointer(_pointer)
    }

    // MARK: Wire format

    init(serializedBytes bytes: some Collection<UInt8>) throws(NanopbError) {
        self.init()
        let array = Array(bytes)
        // see `nanopbEncodedBytes` on why the error is captured rather than
        // propagated straight through the stdlib's untyped `rethrows`
        var failure: NanopbError?
        array.withUnsafeBytes { buffer in
            do throws(NanopbError) {
                try nanopbDecode(into: _pointer, Self.descriptor, buffer)
            } catch {
                failure = error
            }
        }
        if let failure { throw failure }
    }

    init(serializedData data: Data) throws(NanopbError) {
        try self.init(serializedBytes: data)
    }

    func serializedBytes() throws(NanopbError) -> [UInt8] {
        try nanopbEncodedBytes(_pointer, Self.descriptor)
    }

    func serializedData() throws(NanopbError) -> Data {
        try Data(serializedBytes())
    }

    /// Encode into scratch space and hand it to `body` — nothing heap-allocated.
    func withEncodedBytes<R>(_ body: (UnsafeRawBufferPointer) throws -> R) throws -> R {
        let size = try nanopbEncodedSize(_pointer, Self.descriptor)
        return try withUnsafeTemporaryAllocation(byteCount: size, alignment: 1) { buffer in
            let written = try nanopbEncode(_pointer, Self.descriptor, into: buffer)
            return try body(UnsafeRawBufferPointer(rebasing: buffer[..<written]))
        }
    }

    // MARK: Equatable / Hashable

    //
    // Canonical-bytes comparison. nanopb encodes deterministically, except that
    // map fields preserve entry *order* — equal maps built in different orders
    // compare unequal. The SDK uses equality for change detection, where a
    // false "changed" is benign.

    static func == (lhs: Self, rhs: Self) -> Bool {
        if lhs._pointer == rhs._pointer { return true }
        return (try? lhs.serializedBytes()) == (try? rhs.serializedBytes())
    }

    func hash(into hasher: inout Hasher) {
        hasher.combine((try? serializedBytes()) ?? [])
    }
}

/// A protobuf enum. Mirrors SwiftProtobuf's open-enum shape (`UNRECOGNIZED`).
package protocol NanopbEnum: RawRepresentable, Hashable, Sendable where RawValue == Int {
    init()
}

// MARK: - Wire-format primitives

package func nanopbDecode(
    into pointer: UnsafeMutablePointer<some Any>,
    _ descriptor: pb_msgdesc_t,
    _ bytes: UnsafeRawBufferPointer,
) throws(NanopbError) {
    var descriptor = descriptor
    // SAFETY: nanopb reads at most `bytes.count` bytes from the buffer, and
    // the buffer outlives the call because the caller owns it for the
    // duration of `withUnsafeBytes`.
    var stream = lk_pb_istream_from_buffer(
        bytes.baseAddress?.assumingMemoryBound(to: UInt8.self), bytes.count,
    )
    guard lk_pb_decode(&stream, &descriptor, UnsafeMutableRawPointer(pointer)) else {
        throw NanopbError.decodeFailed(stream.errmsg.map { String(cString: $0) } ?? "unknown")
    }
}

package func nanopbEncodedSize(
    _ pointer: UnsafePointer<some Any>, _ descriptor: pb_msgdesc_t,
) throws(NanopbError) -> Int {
    var descriptor = descriptor
    var size = 0
    guard lk_pb_get_encoded_size(&size, &descriptor, UnsafeRawPointer(pointer)) else {
        throw NanopbError.encodeFailed("size")
    }
    return size
}

package func nanopbEncode(
    _ pointer: UnsafePointer<some Any>,
    _ descriptor: pb_msgdesc_t,
    into buffer: UnsafeMutableRawBufferPointer,
) throws(NanopbError) -> Int {
    var descriptor = descriptor
    // SAFETY: the stream is capped at `buffer.count`, so nanopb fails the
    // encode rather than overrunning if the size estimate was short.
    var stream = lk_pb_ostream_from_buffer(
        buffer.baseAddress?.assumingMemoryBound(to: UInt8.self), buffer.count,
    )
    guard lk_pb_encode(&stream, &descriptor, UnsafeRawPointer(pointer)) else {
        throw NanopbError.encodeFailed("encode")
    }
    return stream.bytes_written
}

package func nanopbEncodedBytes(
    _ pointer: UnsafePointer<some Any>, _ descriptor: pb_msgdesc_t,
) throws(NanopbError) -> [UInt8] {
    let size = try nanopbEncodedSize(pointer, descriptor)
    var out = [UInt8](repeating: 0, count: size)
    // `withUnsafeMutableBytes` is untyped `rethrows`, which would erase
    // NanopbError back to `any Error`; capture and rethrow to keep the type.
    var failure: NanopbError?
    var written = 0
    out.withUnsafeMutableBytes { buffer in
        do throws(NanopbError) {
            written = try nanopbEncode(pointer, descriptor, into: buffer)
        } catch {
            failure = error
        }
    }
    if let failure { throw failure }
    if written != size { out.removeLast(size - written) }
    return out
}
