// Generated by scripts/generate-facades.swift — do not edit.
//
// Move-only facades over nanopb's C structs. See Sources/LiveKitNanopb.

import CLiveKitProto
import Foundation
import LiveKitNanopb

struct Livekit_MetricsBatch: NanopbMessage {
    typealias Storage = livekit_MetricsBatch
    static var descriptor: pb_msgdesc_t { livekit_MetricsBatch_msg }
    static var zero: Storage { Storage() }

    var _box: NanopbBox<Storage>
    init() { _box = NanopbBox(zero: Self.zero, descriptor: Self.descriptor) }

    var timestampMs: Int64 {
        get { _box.storage.timestamp_ms?.pointee ?? 0 }
        set { _ensureUnique(); lkSetValue(&_box.storage.timestamp_ms, newValue) }
    }
    var hasTimestampMs: Bool { _box.storage.timestamp_ms != nil }

    var normalizedTimestamp: Google_Protobuf_Timestamp {
        get { lkMessage(_box.storage.normalized_timestamp) }
        set { _ensureUnique(); lkSetMessage(&_box.storage.normalized_timestamp, newValue) }
    }
    var hasNormalizedTimestamp: Bool { _box.storage.normalized_timestamp != nil }

    var strData: [String] {
        get { lkRepeated(_box.storage.str_data_count, _box.storage.str_data) }
        set {
            _ensureUnique()
            var count = _box.storage.str_data_count, base = _box.storage.str_data
            lkSetRepeated(&count, &base, newValue)
            _box.storage.str_data_count = count; _box.storage.str_data = base
        }
    }

    var timeSeries: [Livekit_TimeSeriesMetric] {
        get { lkRepeatedMessages(_box.storage.time_series_count, _box.storage.time_series) }
        set {
            _ensureUnique()
            var count = _box.storage.time_series_count, base = _box.storage.time_series
            lkSetRepeatedMessages(&count, &base, newValue)
            _box.storage.time_series_count = count; _box.storage.time_series = base
        }
    }

    var events: [Livekit_EventMetric] {
        get { lkRepeatedMessages(_box.storage.events_count, _box.storage.events) }
        set {
            _ensureUnique()
            var count = _box.storage.events_count, base = _box.storage.events
            lkSetRepeatedMessages(&count, &base, newValue)
            _box.storage.events_count = count; _box.storage.events = base
        }
    }

}

struct Livekit_TimeSeriesMetric: NanopbMessage {
    typealias Storage = livekit_TimeSeriesMetric
    static var descriptor: pb_msgdesc_t { livekit_TimeSeriesMetric_msg }
    static var zero: Storage { Storage() }

    var _box: NanopbBox<Storage>
    init() { _box = NanopbBox(zero: Self.zero, descriptor: Self.descriptor) }

    var label: UInt32 {
        get { _box.storage.label?.pointee ?? 0 }
        set { _ensureUnique(); lkSetValue(&_box.storage.label, newValue) }
    }
    var hasLabel: Bool { _box.storage.label != nil }

    var participantIdentity: UInt32 {
        get { _box.storage.participant_identity?.pointee ?? 0 }
        set { _ensureUnique(); lkSetValue(&_box.storage.participant_identity, newValue) }
    }
    var hasParticipantIdentity: Bool { _box.storage.participant_identity != nil }

    var trackSid: UInt32 {
        get { _box.storage.track_sid?.pointee ?? 0 }
        set { _ensureUnique(); lkSetValue(&_box.storage.track_sid, newValue) }
    }
    var hasTrackSid: Bool { _box.storage.track_sid != nil }

    var samples: [Livekit_MetricSample] {
        get { lkRepeatedMessages(_box.storage.samples_count, _box.storage.samples) }
        set {
            _ensureUnique()
            var count = _box.storage.samples_count, base = _box.storage.samples
            lkSetRepeatedMessages(&count, &base, newValue)
            _box.storage.samples_count = count; _box.storage.samples = base
        }
    }

    var rid: UInt32 {
        get { _box.storage.rid?.pointee ?? 0 }
        set { _ensureUnique(); lkSetValue(&_box.storage.rid, newValue) }
    }
    var hasRid: Bool { _box.storage.rid != nil }

}

struct Livekit_MetricSample: NanopbMessage {
    typealias Storage = livekit_MetricSample
    static var descriptor: pb_msgdesc_t { livekit_MetricSample_msg }
    static var zero: Storage { Storage() }

    var _box: NanopbBox<Storage>
    init() { _box = NanopbBox(zero: Self.zero, descriptor: Self.descriptor) }

    var timestampMs: Int64 {
        get { _box.storage.timestamp_ms?.pointee ?? 0 }
        set { _ensureUnique(); lkSetValue(&_box.storage.timestamp_ms, newValue) }
    }
    var hasTimestampMs: Bool { _box.storage.timestamp_ms != nil }

    var normalizedTimestamp: Google_Protobuf_Timestamp {
        get { lkMessage(_box.storage.normalized_timestamp) }
        set { _ensureUnique(); lkSetMessage(&_box.storage.normalized_timestamp, newValue) }
    }
    var hasNormalizedTimestamp: Bool { _box.storage.normalized_timestamp != nil }

    var value: Float {
        get { _box.storage.value?.pointee ?? 0 }
        set { _ensureUnique(); lkSetValue(&_box.storage.value, newValue) }
    }
    var hasValue: Bool { _box.storage.value != nil }

}

struct Livekit_EventMetric: NanopbMessage {
    typealias Storage = livekit_EventMetric
    static var descriptor: pb_msgdesc_t { livekit_EventMetric_msg }
    static var zero: Storage { Storage() }

    var _box: NanopbBox<Storage>
    init() { _box = NanopbBox(zero: Self.zero, descriptor: Self.descriptor) }

    var label: UInt32 {
        get { _box.storage.label?.pointee ?? 0 }
        set { _ensureUnique(); lkSetValue(&_box.storage.label, newValue) }
    }
    var hasLabel: Bool { _box.storage.label != nil }

    var participantIdentity: UInt32 {
        get { _box.storage.participant_identity?.pointee ?? 0 }
        set { _ensureUnique(); lkSetValue(&_box.storage.participant_identity, newValue) }
    }
    var hasParticipantIdentity: Bool { _box.storage.participant_identity != nil }

    var trackSid: UInt32 {
        get { _box.storage.track_sid?.pointee ?? 0 }
        set { _ensureUnique(); lkSetValue(&_box.storage.track_sid, newValue) }
    }
    var hasTrackSid: Bool { _box.storage.track_sid != nil }

    var startTimestampMs: Int64 {
        get { _box.storage.start_timestamp_ms?.pointee ?? 0 }
        set { _ensureUnique(); lkSetValue(&_box.storage.start_timestamp_ms, newValue) }
    }
    var hasStartTimestampMs: Bool { _box.storage.start_timestamp_ms != nil }

    var endTimestampMs: Int64 {
        get { _box.storage.end_timestamp_ms?.pointee ?? 0 }
        set { _ensureUnique(); lkSetValue(&_box.storage.end_timestamp_ms, newValue) }
    }
    var hasEndTimestampMs: Bool { _box.storage.end_timestamp_ms != nil }

    var normalizedStartTimestamp: Google_Protobuf_Timestamp {
        get { lkMessage(_box.storage.normalized_start_timestamp) }
        set { _ensureUnique(); lkSetMessage(&_box.storage.normalized_start_timestamp, newValue) }
    }
    var hasNormalizedStartTimestamp: Bool { _box.storage.normalized_start_timestamp != nil }

    var normalizedEndTimestamp: Google_Protobuf_Timestamp {
        get { lkMessage(_box.storage.normalized_end_timestamp) }
        set { _ensureUnique(); lkSetMessage(&_box.storage.normalized_end_timestamp, newValue) }
    }
    var hasNormalizedEndTimestamp: Bool { _box.storage.normalized_end_timestamp != nil }

    var metadata: String {
        get { lkString(_box.storage.metadata) ?? "" }
        set { _ensureUnique(); lkSetString(&_box.storage.metadata, newValue) }
    }
    var hasMetadata: Bool { _box.storage.metadata != nil }
    /// Zero-copy read — borrows nanopb's allocation for the call only.
    func withMetadataBytes<R>(_ body: (UnsafeRawBufferPointer?) throws -> R) rethrows -> R {
        try withLkBytes(_box.storage.metadata, body)
    }

    var rid: UInt32 {
        get { _box.storage.rid?.pointee ?? 0 }
        set { _ensureUnique(); lkSetValue(&_box.storage.rid, newValue) }
    }
    var hasRid: Bool { _box.storage.rid != nil }

}

enum Livekit_MetricLabel: NanopbEnum, CaseIterable {
    case agentsLlmTtft
    case agentsSttTtft
    case agentsTtsTtfb
    case clientVideoSubscriberFreezeCount
    case clientVideoSubscriberTotalFreezeDuration
    case clientVideoSubscriberPauseCount
    case clientVideoSubscriberTotalPausesDuration
    case clientAudioSubscriberConcealedSamples
    case clientAudioSubscriberSilentConcealedSamples
    case clientAudioSubscriberConcealmentEvents
    case clientAudioSubscriberInterruptionCount
    case clientAudioSubscriberTotalInterruptionDuration
    case clientSubscriberJitterBufferDelay
    case clientSubscriberJitterBufferEmittedCount
    case clientVideoPublisherQualityLimitationDurationBandwidth
    case clientVideoPublisherQualityLimitationDurationCpu
    case clientVideoPublisherQualityLimitationDurationOther
    case publisherRtt
    case serverMeshRtt
    case subscriberRtt
    case predefinedMaxValue
    case UNRECOGNIZED(Int)

    init() { self = .agentsLlmTtft }

    init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .agentsLlmTtft
        case 1: self = .agentsSttTtft
        case 2: self = .agentsTtsTtfb
        case 3: self = .clientVideoSubscriberFreezeCount
        case 4: self = .clientVideoSubscriberTotalFreezeDuration
        case 5: self = .clientVideoSubscriberPauseCount
        case 6: self = .clientVideoSubscriberTotalPausesDuration
        case 7: self = .clientAudioSubscriberConcealedSamples
        case 8: self = .clientAudioSubscriberSilentConcealedSamples
        case 9: self = .clientAudioSubscriberConcealmentEvents
        case 10: self = .clientAudioSubscriberInterruptionCount
        case 11: self = .clientAudioSubscriberTotalInterruptionDuration
        case 12: self = .clientSubscriberJitterBufferDelay
        case 13: self = .clientSubscriberJitterBufferEmittedCount
        case 14: self = .clientVideoPublisherQualityLimitationDurationBandwidth
        case 15: self = .clientVideoPublisherQualityLimitationDurationCpu
        case 16: self = .clientVideoPublisherQualityLimitationDurationOther
        case 17: self = .publisherRtt
        case 18: self = .serverMeshRtt
        case 19: self = .subscriberRtt
        case 4096: self = .predefinedMaxValue
        default: self = .UNRECOGNIZED(rawValue)
        }
    }

    var rawValue: Int {
        switch self {
        case .agentsLlmTtft: 0
        case .agentsSttTtft: 1
        case .agentsTtsTtfb: 2
        case .clientVideoSubscriberFreezeCount: 3
        case .clientVideoSubscriberTotalFreezeDuration: 4
        case .clientVideoSubscriberPauseCount: 5
        case .clientVideoSubscriberTotalPausesDuration: 6
        case .clientAudioSubscriberConcealedSamples: 7
        case .clientAudioSubscriberSilentConcealedSamples: 8
        case .clientAudioSubscriberConcealmentEvents: 9
        case .clientAudioSubscriberInterruptionCount: 10
        case .clientAudioSubscriberTotalInterruptionDuration: 11
        case .clientSubscriberJitterBufferDelay: 12
        case .clientSubscriberJitterBufferEmittedCount: 13
        case .clientVideoPublisherQualityLimitationDurationBandwidth: 14
        case .clientVideoPublisherQualityLimitationDurationCpu: 15
        case .clientVideoPublisherQualityLimitationDurationOther: 16
        case .publisherRtt: 17
        case .serverMeshRtt: 18
        case .subscriberRtt: 19
        case .predefinedMaxValue: 4096
        case let .UNRECOGNIZED(value): value
        }
    }

    static var allCases: [Livekit_MetricLabel] {
        [.agentsLlmTtft, .agentsSttTtft, .agentsTtsTtfb, .clientVideoSubscriberFreezeCount, .clientVideoSubscriberTotalFreezeDuration, .clientVideoSubscriberPauseCount, .clientVideoSubscriberTotalPausesDuration, .clientAudioSubscriberConcealedSamples, .clientAudioSubscriberSilentConcealedSamples, .clientAudioSubscriberConcealmentEvents, .clientAudioSubscriberInterruptionCount, .clientAudioSubscriberTotalInterruptionDuration, .clientSubscriberJitterBufferDelay, .clientSubscriberJitterBufferEmittedCount, .clientVideoPublisherQualityLimitationDurationBandwidth, .clientVideoPublisherQualityLimitationDurationCpu, .clientVideoPublisherQualityLimitationDurationOther, .publisherRtt, .serverMeshRtt, .subscriberRtt, .predefinedMaxValue]
    }
}

