// Generated by scripts/generate-swift-protos.swift — do not edit.
//
// Immutable value facades over nanopb's C structs; mutation goes through
// each message's noncopyable Builder. See Sources/LiveKitNanopb.

import Foundation

// Single-module builds compile these sources into the product directly:
// CocoaPods surfaces the C declarations through the umbrella header, while
// the prebuilt xcframework resolves CLiveKitProto via its modulemap — the
// internal import keeps it out of the emitted .swiftinterface.
#if LK_XCFRAMEWORK
internal import CLiveKitProto
#elseif !COCOAPODS
import CLiveKitProto
import LiveKitNanopb
#endif

struct Livekit_MetricsBatch: NanopbMessage, @unchecked Sendable {
    typealias Storage = livekit_MetricsBatch
    static var descriptor: pb_msgdesc_t { livekit_MetricsBatch_msg }
    static var zero: Storage { Storage() }
    /// Shared value returned when a submessage field is absent. Safe to
    /// share because messages are immutable; `modifying` sees the static
    /// reference, so it copies rather than writing through it.
    static let _empty = Livekit_MetricsBatch()

    var _owner: NanopbAnyBox
    var _pointer: UnsafeMutablePointer<Storage>

    init() {
        self.init(_owning: NanopbBox(zero: Self.zero, descriptor: Self.descriptor))
    }

    init(_owning box: NanopbBox<Storage>) {
        _owner = box
        _pointer = box.pointer
    }

    /// Zero-copy view into `owner`'s storage.
    init(_sharing pointer: UnsafeMutablePointer<Storage>, owner: NanopbAnyBox) {
        _owner = owner
        _pointer = pointer
    }

    var timestampMs: Int64 {
        _pointer.pointee.timestamp_ms?.pointee ?? 0
    }
    var hasTimestampMs: Bool { _pointer.pointee.timestamp_ms != nil }

    var normalizedTimestamp: Google_Protobuf_Timestamp {
        _pointer.pointee.normalized_timestamp.map { Google_Protobuf_Timestamp(_sharing: $0, owner: _owner) } ?? Google_Protobuf_Timestamp._empty
    }
    var hasNormalizedTimestamp: Bool { _pointer.pointee.normalized_timestamp != nil }

    var strData: [String] {
        lkRepeated(_pointer.pointee.str_data_count, _pointer.pointee.str_data)
    }

    var timeSeries: [Livekit_TimeSeriesMetric] {
        lkViews(_pointer.pointee.time_series_count, _pointer.pointee.time_series, owner: _owner)
    }

    var events: [Livekit_EventMetric] {
        lkViews(_pointer.pointee.events_count, _pointer.pointee.events, owner: _owner)
    }

    /// Mutation lives here. `~Copyable` means the compiler proves there is
    /// never a second live handle to this storage, so no uniqueness check is
    /// needed and `build()` publishes storage nothing can still mutate.
    struct Builder: ~Copyable {
        let _box: NanopbBox<Storage>
        var _owner: NanopbAnyBox { _box }
        var _pointer: UnsafeMutablePointer<Storage> { _box.pointer }

        init() { _box = NanopbBox(zero: Livekit_MetricsBatch.zero, descriptor: Livekit_MetricsBatch.descriptor) }
        init(_adopting box: NanopbBox<Storage>) { _box = box }
        consuming func build() -> Livekit_MetricsBatch { Livekit_MetricsBatch(_owning: _box) }

        var timestampMs: Int64 {
            get { _pointer.pointee.timestamp_ms?.pointee ?? 0 }
            nonmutating set { lkSetValue(&_pointer.pointee.timestamp_ms, newValue) }
        }

        var normalizedTimestamp: Google_Protobuf_Timestamp {
            get { _pointer.pointee.normalized_timestamp.map { Google_Protobuf_Timestamp(_sharing: $0, owner: _owner) } ?? Google_Protobuf_Timestamp._empty }
            nonmutating set { lkSetMessage(&_pointer.pointee.normalized_timestamp, newValue) }
        }

        var strData: [String] {
            get { lkRepeated(_pointer.pointee.str_data_count, _pointer.pointee.str_data) }
            nonmutating set {
                var count = _pointer.pointee.str_data_count, base = _pointer.pointee.str_data
                lkSetRepeated(&count, &base, newValue)
                _pointer.pointee.str_data_count = count; _pointer.pointee.str_data = base
            }
        }

        var timeSeries: [Livekit_TimeSeriesMetric] {
            get { lkViews(_pointer.pointee.time_series_count, _pointer.pointee.time_series, owner: _owner) }
            nonmutating set {
                var count = _pointer.pointee.time_series_count, base = _pointer.pointee.time_series
                lkSetRepeatedMessages(&count, &base, newValue)
                _pointer.pointee.time_series_count = count; _pointer.pointee.time_series = base
            }
        }

        var events: [Livekit_EventMetric] {
            get { lkViews(_pointer.pointee.events_count, _pointer.pointee.events, owner: _owner) }
            nonmutating set {
                var count = _pointer.pointee.events_count, base = _pointer.pointee.events
                lkSetRepeatedMessages(&count, &base, newValue)
                _pointer.pointee.events_count = count; _pointer.pointee.events = base
            }
        }

    }

    static func with(_ populate: (inout Builder) throws -> Void) rethrows -> Self {
        var builder = Builder()
        try populate(&builder)
        return builder.build()
    }

    /// This message with `populate` applied. `consuming` ends the caller's
    /// ownership, so when nothing else holds the storage the mutation happens
    /// in place; otherwise it copies once for the whole batch, not per field.
    consuming func modifying(_ populate: (inout Builder) throws -> Void) rethrows -> Self {
        if _ownsItsStorage, isKnownUniquelyReferenced(&_owner) {
            var builder = Builder(_adopting: unsafeDowncast(_owner, to: NanopbBox<Storage>.self))
            try populate(&builder)
            return builder.build()
        }
        var builder = Builder()
        lkOverwrite(builder._pointer, with: self)
        try populate(&builder)
        return builder.build()
    }
}

struct Livekit_TimeSeriesMetric: NanopbMessage, @unchecked Sendable {
    typealias Storage = livekit_TimeSeriesMetric
    static var descriptor: pb_msgdesc_t { livekit_TimeSeriesMetric_msg }
    static var zero: Storage { Storage() }
    /// Shared value returned when a submessage field is absent. Safe to
    /// share because messages are immutable; `modifying` sees the static
    /// reference, so it copies rather than writing through it.
    static let _empty = Livekit_TimeSeriesMetric()

    var _owner: NanopbAnyBox
    var _pointer: UnsafeMutablePointer<Storage>

    init() {
        self.init(_owning: NanopbBox(zero: Self.zero, descriptor: Self.descriptor))
    }

    init(_owning box: NanopbBox<Storage>) {
        _owner = box
        _pointer = box.pointer
    }

    /// Zero-copy view into `owner`'s storage.
    init(_sharing pointer: UnsafeMutablePointer<Storage>, owner: NanopbAnyBox) {
        _owner = owner
        _pointer = pointer
    }

    var label: UInt32 {
        _pointer.pointee.label?.pointee ?? 0
    }
    var hasLabel: Bool { _pointer.pointee.label != nil }

    var participantIdentity: UInt32 {
        _pointer.pointee.participant_identity?.pointee ?? 0
    }
    var hasParticipantIdentity: Bool { _pointer.pointee.participant_identity != nil }

    var trackSid: UInt32 {
        _pointer.pointee.track_sid?.pointee ?? 0
    }
    var hasTrackSid: Bool { _pointer.pointee.track_sid != nil }

    var samples: [Livekit_MetricSample] {
        lkViews(_pointer.pointee.samples_count, _pointer.pointee.samples, owner: _owner)
    }

    var rid: UInt32 {
        _pointer.pointee.rid?.pointee ?? 0
    }
    var hasRid: Bool { _pointer.pointee.rid != nil }

    /// Mutation lives here. `~Copyable` means the compiler proves there is
    /// never a second live handle to this storage, so no uniqueness check is
    /// needed and `build()` publishes storage nothing can still mutate.
    struct Builder: ~Copyable {
        let _box: NanopbBox<Storage>
        var _owner: NanopbAnyBox { _box }
        var _pointer: UnsafeMutablePointer<Storage> { _box.pointer }

        init() { _box = NanopbBox(zero: Livekit_TimeSeriesMetric.zero, descriptor: Livekit_TimeSeriesMetric.descriptor) }
        init(_adopting box: NanopbBox<Storage>) { _box = box }
        consuming func build() -> Livekit_TimeSeriesMetric { Livekit_TimeSeriesMetric(_owning: _box) }

        var label: UInt32 {
            get { _pointer.pointee.label?.pointee ?? 0 }
            nonmutating set { lkSetValue(&_pointer.pointee.label, newValue) }
        }

        var participantIdentity: UInt32 {
            get { _pointer.pointee.participant_identity?.pointee ?? 0 }
            nonmutating set { lkSetValue(&_pointer.pointee.participant_identity, newValue) }
        }

        var trackSid: UInt32 {
            get { _pointer.pointee.track_sid?.pointee ?? 0 }
            nonmutating set { lkSetValue(&_pointer.pointee.track_sid, newValue) }
        }

        var samples: [Livekit_MetricSample] {
            get { lkViews(_pointer.pointee.samples_count, _pointer.pointee.samples, owner: _owner) }
            nonmutating set {
                var count = _pointer.pointee.samples_count, base = _pointer.pointee.samples
                lkSetRepeatedMessages(&count, &base, newValue)
                _pointer.pointee.samples_count = count; _pointer.pointee.samples = base
            }
        }

        var rid: UInt32 {
            get { _pointer.pointee.rid?.pointee ?? 0 }
            nonmutating set { lkSetValue(&_pointer.pointee.rid, newValue) }
        }

    }

    static func with(_ populate: (inout Builder) throws -> Void) rethrows -> Self {
        var builder = Builder()
        try populate(&builder)
        return builder.build()
    }

    /// This message with `populate` applied. `consuming` ends the caller's
    /// ownership, so when nothing else holds the storage the mutation happens
    /// in place; otherwise it copies once for the whole batch, not per field.
    consuming func modifying(_ populate: (inout Builder) throws -> Void) rethrows -> Self {
        if _ownsItsStorage, isKnownUniquelyReferenced(&_owner) {
            var builder = Builder(_adopting: unsafeDowncast(_owner, to: NanopbBox<Storage>.self))
            try populate(&builder)
            return builder.build()
        }
        var builder = Builder()
        lkOverwrite(builder._pointer, with: self)
        try populate(&builder)
        return builder.build()
    }
}

struct Livekit_MetricSample: NanopbMessage, @unchecked Sendable {
    typealias Storage = livekit_MetricSample
    static var descriptor: pb_msgdesc_t { livekit_MetricSample_msg }
    static var zero: Storage { Storage() }
    /// Shared value returned when a submessage field is absent. Safe to
    /// share because messages are immutable; `modifying` sees the static
    /// reference, so it copies rather than writing through it.
    static let _empty = Livekit_MetricSample()

    var _owner: NanopbAnyBox
    var _pointer: UnsafeMutablePointer<Storage>

    init() {
        self.init(_owning: NanopbBox(zero: Self.zero, descriptor: Self.descriptor))
    }

    init(_owning box: NanopbBox<Storage>) {
        _owner = box
        _pointer = box.pointer
    }

    /// Zero-copy view into `owner`'s storage.
    init(_sharing pointer: UnsafeMutablePointer<Storage>, owner: NanopbAnyBox) {
        _owner = owner
        _pointer = pointer
    }

    var timestampMs: Int64 {
        _pointer.pointee.timestamp_ms?.pointee ?? 0
    }
    var hasTimestampMs: Bool { _pointer.pointee.timestamp_ms != nil }

    var normalizedTimestamp: Google_Protobuf_Timestamp {
        _pointer.pointee.normalized_timestamp.map { Google_Protobuf_Timestamp(_sharing: $0, owner: _owner) } ?? Google_Protobuf_Timestamp._empty
    }
    var hasNormalizedTimestamp: Bool { _pointer.pointee.normalized_timestamp != nil }

    var value: Float {
        _pointer.pointee.value?.pointee ?? 0
    }
    var hasValue: Bool { _pointer.pointee.value != nil }

    /// Mutation lives here. `~Copyable` means the compiler proves there is
    /// never a second live handle to this storage, so no uniqueness check is
    /// needed and `build()` publishes storage nothing can still mutate.
    struct Builder: ~Copyable {
        let _box: NanopbBox<Storage>
        var _owner: NanopbAnyBox { _box }
        var _pointer: UnsafeMutablePointer<Storage> { _box.pointer }

        init() { _box = NanopbBox(zero: Livekit_MetricSample.zero, descriptor: Livekit_MetricSample.descriptor) }
        init(_adopting box: NanopbBox<Storage>) { _box = box }
        consuming func build() -> Livekit_MetricSample { Livekit_MetricSample(_owning: _box) }

        var timestampMs: Int64 {
            get { _pointer.pointee.timestamp_ms?.pointee ?? 0 }
            nonmutating set { lkSetValue(&_pointer.pointee.timestamp_ms, newValue) }
        }

        var normalizedTimestamp: Google_Protobuf_Timestamp {
            get { _pointer.pointee.normalized_timestamp.map { Google_Protobuf_Timestamp(_sharing: $0, owner: _owner) } ?? Google_Protobuf_Timestamp._empty }
            nonmutating set { lkSetMessage(&_pointer.pointee.normalized_timestamp, newValue) }
        }

        var value: Float {
            get { _pointer.pointee.value?.pointee ?? 0 }
            nonmutating set { lkSetValue(&_pointer.pointee.value, newValue) }
        }

    }

    static func with(_ populate: (inout Builder) throws -> Void) rethrows -> Self {
        var builder = Builder()
        try populate(&builder)
        return builder.build()
    }

    /// This message with `populate` applied. `consuming` ends the caller's
    /// ownership, so when nothing else holds the storage the mutation happens
    /// in place; otherwise it copies once for the whole batch, not per field.
    consuming func modifying(_ populate: (inout Builder) throws -> Void) rethrows -> Self {
        if _ownsItsStorage, isKnownUniquelyReferenced(&_owner) {
            var builder = Builder(_adopting: unsafeDowncast(_owner, to: NanopbBox<Storage>.self))
            try populate(&builder)
            return builder.build()
        }
        var builder = Builder()
        lkOverwrite(builder._pointer, with: self)
        try populate(&builder)
        return builder.build()
    }
}

struct Livekit_EventMetric: NanopbMessage, @unchecked Sendable {
    typealias Storage = livekit_EventMetric
    static var descriptor: pb_msgdesc_t { livekit_EventMetric_msg }
    static var zero: Storage { Storage() }
    /// Shared value returned when a submessage field is absent. Safe to
    /// share because messages are immutable; `modifying` sees the static
    /// reference, so it copies rather than writing through it.
    static let _empty = Livekit_EventMetric()

    var _owner: NanopbAnyBox
    var _pointer: UnsafeMutablePointer<Storage>

    init() {
        self.init(_owning: NanopbBox(zero: Self.zero, descriptor: Self.descriptor))
    }

    init(_owning box: NanopbBox<Storage>) {
        _owner = box
        _pointer = box.pointer
    }

    /// Zero-copy view into `owner`'s storage.
    init(_sharing pointer: UnsafeMutablePointer<Storage>, owner: NanopbAnyBox) {
        _owner = owner
        _pointer = pointer
    }

    var label: UInt32 {
        _pointer.pointee.label?.pointee ?? 0
    }
    var hasLabel: Bool { _pointer.pointee.label != nil }

    var participantIdentity: UInt32 {
        _pointer.pointee.participant_identity?.pointee ?? 0
    }
    var hasParticipantIdentity: Bool { _pointer.pointee.participant_identity != nil }

    var trackSid: UInt32 {
        _pointer.pointee.track_sid?.pointee ?? 0
    }
    var hasTrackSid: Bool { _pointer.pointee.track_sid != nil }

    var startTimestampMs: Int64 {
        _pointer.pointee.start_timestamp_ms?.pointee ?? 0
    }
    var hasStartTimestampMs: Bool { _pointer.pointee.start_timestamp_ms != nil }

    var endTimestampMs: Int64 {
        _pointer.pointee.end_timestamp_ms?.pointee ?? 0
    }
    var hasEndTimestampMs: Bool { _pointer.pointee.end_timestamp_ms != nil }

    var normalizedStartTimestamp: Google_Protobuf_Timestamp {
        _pointer.pointee.normalized_start_timestamp.map { Google_Protobuf_Timestamp(_sharing: $0, owner: _owner) } ?? Google_Protobuf_Timestamp._empty
    }
    var hasNormalizedStartTimestamp: Bool { _pointer.pointee.normalized_start_timestamp != nil }

    var normalizedEndTimestamp: Google_Protobuf_Timestamp {
        _pointer.pointee.normalized_end_timestamp.map { Google_Protobuf_Timestamp(_sharing: $0, owner: _owner) } ?? Google_Protobuf_Timestamp._empty
    }
    var hasNormalizedEndTimestamp: Bool { _pointer.pointee.normalized_end_timestamp != nil }

    var metadata: String {
        lkString(_pointer.pointee.metadata) ?? ""
    }
    var hasMetadata: Bool { _pointer.pointee.metadata != nil }

    var rid: UInt32 {
        _pointer.pointee.rid?.pointee ?? 0
    }
    var hasRid: Bool { _pointer.pointee.rid != nil }

    /// Mutation lives here. `~Copyable` means the compiler proves there is
    /// never a second live handle to this storage, so no uniqueness check is
    /// needed and `build()` publishes storage nothing can still mutate.
    struct Builder: ~Copyable {
        let _box: NanopbBox<Storage>
        var _owner: NanopbAnyBox { _box }
        var _pointer: UnsafeMutablePointer<Storage> { _box.pointer }

        init() { _box = NanopbBox(zero: Livekit_EventMetric.zero, descriptor: Livekit_EventMetric.descriptor) }
        init(_adopting box: NanopbBox<Storage>) { _box = box }
        consuming func build() -> Livekit_EventMetric { Livekit_EventMetric(_owning: _box) }

        var label: UInt32 {
            get { _pointer.pointee.label?.pointee ?? 0 }
            nonmutating set { lkSetValue(&_pointer.pointee.label, newValue) }
        }

        var participantIdentity: UInt32 {
            get { _pointer.pointee.participant_identity?.pointee ?? 0 }
            nonmutating set { lkSetValue(&_pointer.pointee.participant_identity, newValue) }
        }

        var trackSid: UInt32 {
            get { _pointer.pointee.track_sid?.pointee ?? 0 }
            nonmutating set { lkSetValue(&_pointer.pointee.track_sid, newValue) }
        }

        var startTimestampMs: Int64 {
            get { _pointer.pointee.start_timestamp_ms?.pointee ?? 0 }
            nonmutating set { lkSetValue(&_pointer.pointee.start_timestamp_ms, newValue) }
        }

        var endTimestampMs: Int64 {
            get { _pointer.pointee.end_timestamp_ms?.pointee ?? 0 }
            nonmutating set { lkSetValue(&_pointer.pointee.end_timestamp_ms, newValue) }
        }

        var normalizedStartTimestamp: Google_Protobuf_Timestamp {
            get { _pointer.pointee.normalized_start_timestamp.map { Google_Protobuf_Timestamp(_sharing: $0, owner: _owner) } ?? Google_Protobuf_Timestamp._empty }
            nonmutating set { lkSetMessage(&_pointer.pointee.normalized_start_timestamp, newValue) }
        }

        var normalizedEndTimestamp: Google_Protobuf_Timestamp {
            get { _pointer.pointee.normalized_end_timestamp.map { Google_Protobuf_Timestamp(_sharing: $0, owner: _owner) } ?? Google_Protobuf_Timestamp._empty }
            nonmutating set { lkSetMessage(&_pointer.pointee.normalized_end_timestamp, newValue) }
        }

        var metadata: String {
            get { lkString(_pointer.pointee.metadata) ?? "" }
            nonmutating set { lkSetString(&_pointer.pointee.metadata, newValue) }
        }

        var rid: UInt32 {
            get { _pointer.pointee.rid?.pointee ?? 0 }
            nonmutating set { lkSetValue(&_pointer.pointee.rid, newValue) }
        }

    }

    static func with(_ populate: (inout Builder) throws -> Void) rethrows -> Self {
        var builder = Builder()
        try populate(&builder)
        return builder.build()
    }

    /// This message with `populate` applied. `consuming` ends the caller's
    /// ownership, so when nothing else holds the storage the mutation happens
    /// in place; otherwise it copies once for the whole batch, not per field.
    consuming func modifying(_ populate: (inout Builder) throws -> Void) rethrows -> Self {
        if _ownsItsStorage, isKnownUniquelyReferenced(&_owner) {
            var builder = Builder(_adopting: unsafeDowncast(_owner, to: NanopbBox<Storage>.self))
            try populate(&builder)
            return builder.build()
        }
        var builder = Builder()
        lkOverwrite(builder._pointer, with: self)
        try populate(&builder)
        return builder.build()
    }
}

enum Livekit_MetricLabel: NanopbEnum, CaseIterable {
    case agentsLlmTtft
    case agentsSttTtft
    case agentsTtsTtfb
    case clientVideoSubscriberFreezeCount
    case clientVideoSubscriberTotalFreezeDuration
    case clientVideoSubscriberPauseCount
    case clientVideoSubscriberTotalPausesDuration
    case clientAudioSubscriberConcealedSamples
    case clientAudioSubscriberSilentConcealedSamples
    case clientAudioSubscriberConcealmentEvents
    case clientAudioSubscriberInterruptionCount
    case clientAudioSubscriberTotalInterruptionDuration
    case clientSubscriberJitterBufferDelay
    case clientSubscriberJitterBufferEmittedCount
    case clientVideoPublisherQualityLimitationDurationBandwidth
    case clientVideoPublisherQualityLimitationDurationCpu
    case clientVideoPublisherQualityLimitationDurationOther
    case publisherRtt
    case serverMeshRtt
    case subscriberRtt
    case predefinedMaxValue
    case UNRECOGNIZED(Int)

    init() { self = .agentsLlmTtft }

    init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .agentsLlmTtft
        case 1: self = .agentsSttTtft
        case 2: self = .agentsTtsTtfb
        case 3: self = .clientVideoSubscriberFreezeCount
        case 4: self = .clientVideoSubscriberTotalFreezeDuration
        case 5: self = .clientVideoSubscriberPauseCount
        case 6: self = .clientVideoSubscriberTotalPausesDuration
        case 7: self = .clientAudioSubscriberConcealedSamples
        case 8: self = .clientAudioSubscriberSilentConcealedSamples
        case 9: self = .clientAudioSubscriberConcealmentEvents
        case 10: self = .clientAudioSubscriberInterruptionCount
        case 11: self = .clientAudioSubscriberTotalInterruptionDuration
        case 12: self = .clientSubscriberJitterBufferDelay
        case 13: self = .clientSubscriberJitterBufferEmittedCount
        case 14: self = .clientVideoPublisherQualityLimitationDurationBandwidth
        case 15: self = .clientVideoPublisherQualityLimitationDurationCpu
        case 16: self = .clientVideoPublisherQualityLimitationDurationOther
        case 17: self = .publisherRtt
        case 18: self = .serverMeshRtt
        case 19: self = .subscriberRtt
        case 4096: self = .predefinedMaxValue
        default: self = .UNRECOGNIZED(rawValue)
        }
    }

    var rawValue: Int {
        switch self {
        case .agentsLlmTtft: 0
        case .agentsSttTtft: 1
        case .agentsTtsTtfb: 2
        case .clientVideoSubscriberFreezeCount: 3
        case .clientVideoSubscriberTotalFreezeDuration: 4
        case .clientVideoSubscriberPauseCount: 5
        case .clientVideoSubscriberTotalPausesDuration: 6
        case .clientAudioSubscriberConcealedSamples: 7
        case .clientAudioSubscriberSilentConcealedSamples: 8
        case .clientAudioSubscriberConcealmentEvents: 9
        case .clientAudioSubscriberInterruptionCount: 10
        case .clientAudioSubscriberTotalInterruptionDuration: 11
        case .clientSubscriberJitterBufferDelay: 12
        case .clientSubscriberJitterBufferEmittedCount: 13
        case .clientVideoPublisherQualityLimitationDurationBandwidth: 14
        case .clientVideoPublisherQualityLimitationDurationCpu: 15
        case .clientVideoPublisherQualityLimitationDurationOther: 16
        case .publisherRtt: 17
        case .serverMeshRtt: 18
        case .subscriberRtt: 19
        case .predefinedMaxValue: 4096
        case let .UNRECOGNIZED(value): value
        }
    }

    static var allCases: [Livekit_MetricLabel] {
        [.agentsLlmTtft, .agentsSttTtft, .agentsTtsTtfb, .clientVideoSubscriberFreezeCount, .clientVideoSubscriberTotalFreezeDuration, .clientVideoSubscriberPauseCount, .clientVideoSubscriberTotalPausesDuration, .clientAudioSubscriberConcealedSamples, .clientAudioSubscriberSilentConcealedSamples, .clientAudioSubscriberConcealmentEvents, .clientAudioSubscriberInterruptionCount, .clientAudioSubscriberTotalInterruptionDuration, .clientSubscriberJitterBufferDelay, .clientSubscriberJitterBufferEmittedCount, .clientVideoPublisherQualityLimitationDurationBandwidth, .clientVideoPublisherQualityLimitationDurationCpu, .clientVideoPublisherQualityLimitationDurationOther, .publisherRtt, .serverMeshRtt, .subscriberRtt, .predefinedMaxValue]
    }
}

