// Generated by scripts/generate-swift-protos.swift — do not edit.
//
// Immutable value facades over nanopb's C structs. Every message is the
// one generic NanopbMsg<Storage> — this file adds only a storage
// conformance, a typealias and the field accessors, so the schema
// contributes no Swift types of its own. Mutation goes through the
// noncopyable Builder. See Sources/LiveKitNanopb.

import Foundation

// Single-module builds compile these sources into the product directly:
// CocoaPods surfaces the C declarations through the umbrella header, while
// the prebuilt xcframework resolves CLiveKitProto via its modulemap — the
// internal import keeps it out of the emitted .swiftinterface.
#if LK_XCFRAMEWORK
package import CLiveKitProto
#elseif !COCOAPODS
import CLiveKitProto
import LiveKitNanopb
#endif

extension livekit_MetricsBatch: NanopbStorage {
    package static var descriptor: pb_msgdesc_t { livekit_MetricsBatch_msg }
    package static let _emptyBox = NanopbBox<livekit_MetricsBatch>(zero: livekit_MetricsBatch(), descriptor: livekit_MetricsBatch_msg)
}
typealias Livekit_MetricsBatch = NanopbMsg<livekit_MetricsBatch>
extension Livekit_MetricsBatch {
    var timestampMs: Int64 {
        _pointer.pointee.timestamp_ms?.pointee ?? 0
    }
    var hasTimestampMs: Bool { _pointer.pointee.timestamp_ms != nil }

    var normalizedTimestamp: Google_Protobuf_Timestamp {
        _pointer.pointee.normalized_timestamp.map { Google_Protobuf_Timestamp(_sharing: $0, owner: _owner) } ?? Google_Protobuf_Timestamp._empty
    }
    var hasNormalizedTimestamp: Bool { _pointer.pointee.normalized_timestamp != nil }

    var strData: [String] {
        lkRepeated(_pointer.pointee.str_data_count, _pointer.pointee.str_data)
    }

    var timeSeries: [Livekit_TimeSeriesMetric] {
        lkViews(_pointer.pointee.time_series_count, _pointer.pointee.time_series, owner: _owner)
    }

    var events: [Livekit_EventMetric] {
        lkViews(_pointer.pointee.events_count, _pointer.pointee.events, owner: _owner)
    }

}

extension Livekit_MetricsBatch.Builder {
    var timestampMs: Int64 {
        get { _pointer.pointee.timestamp_ms?.pointee ?? 0 }
        nonmutating set { lkSetValue(&_pointer.pointee.timestamp_ms, newValue) }
    }

    var normalizedTimestamp: Google_Protobuf_Timestamp {
        get { _pointer.pointee.normalized_timestamp.map { Google_Protobuf_Timestamp(_sharing: $0, owner: _box) } ?? Google_Protobuf_Timestamp._empty }
        nonmutating set { lkSetMessage(&_pointer.pointee.normalized_timestamp, newValue) }
    }

    var strData: [String] {
        get { lkRepeated(_pointer.pointee.str_data_count, _pointer.pointee.str_data) }
        nonmutating set {
            var count = _pointer.pointee.str_data_count, base = _pointer.pointee.str_data
            lkSetRepeated(&count, &base, newValue)
            _pointer.pointee.str_data_count = count; _pointer.pointee.str_data = base
        }
    }

    var timeSeries: [Livekit_TimeSeriesMetric] {
        get { lkViews(_pointer.pointee.time_series_count, _pointer.pointee.time_series, owner: _box) }
        nonmutating set {
            var count = _pointer.pointee.time_series_count, base = _pointer.pointee.time_series
            lkSetRepeatedMessages(&count, &base, newValue)
            _pointer.pointee.time_series_count = count; _pointer.pointee.time_series = base
        }
    }

    var events: [Livekit_EventMetric] {
        get { lkViews(_pointer.pointee.events_count, _pointer.pointee.events, owner: _box) }
        nonmutating set {
            var count = _pointer.pointee.events_count, base = _pointer.pointee.events
            lkSetRepeatedMessages(&count, &base, newValue)
            _pointer.pointee.events_count = count; _pointer.pointee.events = base
        }
    }

}

extension livekit_TimeSeriesMetric: NanopbStorage {
    package static var descriptor: pb_msgdesc_t { livekit_TimeSeriesMetric_msg }
    package static let _emptyBox = NanopbBox<livekit_TimeSeriesMetric>(zero: livekit_TimeSeriesMetric(), descriptor: livekit_TimeSeriesMetric_msg)
}
typealias Livekit_TimeSeriesMetric = NanopbMsg<livekit_TimeSeriesMetric>
extension Livekit_TimeSeriesMetric {
    var label: UInt32 {
        _pointer.pointee.label?.pointee ?? 0
    }
    var hasLabel: Bool { _pointer.pointee.label != nil }

    var participantIdentity: UInt32 {
        _pointer.pointee.participant_identity?.pointee ?? 0
    }
    var hasParticipantIdentity: Bool { _pointer.pointee.participant_identity != nil }

    var trackSid: UInt32 {
        _pointer.pointee.track_sid?.pointee ?? 0
    }
    var hasTrackSid: Bool { _pointer.pointee.track_sid != nil }

    var samples: [Livekit_MetricSample] {
        lkViews(_pointer.pointee.samples_count, _pointer.pointee.samples, owner: _owner)
    }

    var rid: UInt32 {
        _pointer.pointee.rid?.pointee ?? 0
    }
    var hasRid: Bool { _pointer.pointee.rid != nil }

}

extension Livekit_TimeSeriesMetric.Builder {
    var label: UInt32 {
        get { _pointer.pointee.label?.pointee ?? 0 }
        nonmutating set { lkSetValue(&_pointer.pointee.label, newValue) }
    }

    var participantIdentity: UInt32 {
        get { _pointer.pointee.participant_identity?.pointee ?? 0 }
        nonmutating set { lkSetValue(&_pointer.pointee.participant_identity, newValue) }
    }

    var trackSid: UInt32 {
        get { _pointer.pointee.track_sid?.pointee ?? 0 }
        nonmutating set { lkSetValue(&_pointer.pointee.track_sid, newValue) }
    }

    var samples: [Livekit_MetricSample] {
        get { lkViews(_pointer.pointee.samples_count, _pointer.pointee.samples, owner: _box) }
        nonmutating set {
            var count = _pointer.pointee.samples_count, base = _pointer.pointee.samples
            lkSetRepeatedMessages(&count, &base, newValue)
            _pointer.pointee.samples_count = count; _pointer.pointee.samples = base
        }
    }

    var rid: UInt32 {
        get { _pointer.pointee.rid?.pointee ?? 0 }
        nonmutating set { lkSetValue(&_pointer.pointee.rid, newValue) }
    }

}

extension livekit_MetricSample: NanopbStorage {
    package static var descriptor: pb_msgdesc_t { livekit_MetricSample_msg }
    package static let _emptyBox = NanopbBox<livekit_MetricSample>(zero: livekit_MetricSample(), descriptor: livekit_MetricSample_msg)
}
typealias Livekit_MetricSample = NanopbMsg<livekit_MetricSample>
extension Livekit_MetricSample {
    var timestampMs: Int64 {
        _pointer.pointee.timestamp_ms?.pointee ?? 0
    }
    var hasTimestampMs: Bool { _pointer.pointee.timestamp_ms != nil }

    var normalizedTimestamp: Google_Protobuf_Timestamp {
        _pointer.pointee.normalized_timestamp.map { Google_Protobuf_Timestamp(_sharing: $0, owner: _owner) } ?? Google_Protobuf_Timestamp._empty
    }
    var hasNormalizedTimestamp: Bool { _pointer.pointee.normalized_timestamp != nil }

    var value: Float {
        _pointer.pointee.value?.pointee ?? 0
    }
    var hasValue: Bool { _pointer.pointee.value != nil }

}

extension Livekit_MetricSample.Builder {
    var timestampMs: Int64 {
        get { _pointer.pointee.timestamp_ms?.pointee ?? 0 }
        nonmutating set { lkSetValue(&_pointer.pointee.timestamp_ms, newValue) }
    }

    var normalizedTimestamp: Google_Protobuf_Timestamp {
        get { _pointer.pointee.normalized_timestamp.map { Google_Protobuf_Timestamp(_sharing: $0, owner: _box) } ?? Google_Protobuf_Timestamp._empty }
        nonmutating set { lkSetMessage(&_pointer.pointee.normalized_timestamp, newValue) }
    }

    var value: Float {
        get { _pointer.pointee.value?.pointee ?? 0 }
        nonmutating set { lkSetValue(&_pointer.pointee.value, newValue) }
    }

}

extension livekit_EventMetric: NanopbStorage {
    package static var descriptor: pb_msgdesc_t { livekit_EventMetric_msg }
    package static let _emptyBox = NanopbBox<livekit_EventMetric>(zero: livekit_EventMetric(), descriptor: livekit_EventMetric_msg)
}
typealias Livekit_EventMetric = NanopbMsg<livekit_EventMetric>
extension Livekit_EventMetric {
    var label: UInt32 {
        _pointer.pointee.label?.pointee ?? 0
    }
    var hasLabel: Bool { _pointer.pointee.label != nil }

    var participantIdentity: UInt32 {
        _pointer.pointee.participant_identity?.pointee ?? 0
    }
    var hasParticipantIdentity: Bool { _pointer.pointee.participant_identity != nil }

    var trackSid: UInt32 {
        _pointer.pointee.track_sid?.pointee ?? 0
    }
    var hasTrackSid: Bool { _pointer.pointee.track_sid != nil }

    var startTimestampMs: Int64 {
        _pointer.pointee.start_timestamp_ms?.pointee ?? 0
    }
    var hasStartTimestampMs: Bool { _pointer.pointee.start_timestamp_ms != nil }

    var endTimestampMs: Int64 {
        _pointer.pointee.end_timestamp_ms?.pointee ?? 0
    }
    var hasEndTimestampMs: Bool { _pointer.pointee.end_timestamp_ms != nil }

    var normalizedStartTimestamp: Google_Protobuf_Timestamp {
        _pointer.pointee.normalized_start_timestamp.map { Google_Protobuf_Timestamp(_sharing: $0, owner: _owner) } ?? Google_Protobuf_Timestamp._empty
    }
    var hasNormalizedStartTimestamp: Bool { _pointer.pointee.normalized_start_timestamp != nil }

    var normalizedEndTimestamp: Google_Protobuf_Timestamp {
        _pointer.pointee.normalized_end_timestamp.map { Google_Protobuf_Timestamp(_sharing: $0, owner: _owner) } ?? Google_Protobuf_Timestamp._empty
    }
    var hasNormalizedEndTimestamp: Bool { _pointer.pointee.normalized_end_timestamp != nil }

    var metadata: String {
        lkString(_pointer.pointee.metadata) ?? ""
    }
    var hasMetadata: Bool { _pointer.pointee.metadata != nil }

    var rid: UInt32 {
        _pointer.pointee.rid?.pointee ?? 0
    }
    var hasRid: Bool { _pointer.pointee.rid != nil }

}

extension Livekit_EventMetric.Builder {
    var label: UInt32 {
        get { _pointer.pointee.label?.pointee ?? 0 }
        nonmutating set { lkSetValue(&_pointer.pointee.label, newValue) }
    }

    var participantIdentity: UInt32 {
        get { _pointer.pointee.participant_identity?.pointee ?? 0 }
        nonmutating set { lkSetValue(&_pointer.pointee.participant_identity, newValue) }
    }

    var trackSid: UInt32 {
        get { _pointer.pointee.track_sid?.pointee ?? 0 }
        nonmutating set { lkSetValue(&_pointer.pointee.track_sid, newValue) }
    }

    var startTimestampMs: Int64 {
        get { _pointer.pointee.start_timestamp_ms?.pointee ?? 0 }
        nonmutating set { lkSetValue(&_pointer.pointee.start_timestamp_ms, newValue) }
    }

    var endTimestampMs: Int64 {
        get { _pointer.pointee.end_timestamp_ms?.pointee ?? 0 }
        nonmutating set { lkSetValue(&_pointer.pointee.end_timestamp_ms, newValue) }
    }

    var normalizedStartTimestamp: Google_Protobuf_Timestamp {
        get { _pointer.pointee.normalized_start_timestamp.map { Google_Protobuf_Timestamp(_sharing: $0, owner: _box) } ?? Google_Protobuf_Timestamp._empty }
        nonmutating set { lkSetMessage(&_pointer.pointee.normalized_start_timestamp, newValue) }
    }

    var normalizedEndTimestamp: Google_Protobuf_Timestamp {
        get { _pointer.pointee.normalized_end_timestamp.map { Google_Protobuf_Timestamp(_sharing: $0, owner: _box) } ?? Google_Protobuf_Timestamp._empty }
        nonmutating set { lkSetMessage(&_pointer.pointee.normalized_end_timestamp, newValue) }
    }

    var metadata: String {
        get { lkString(_pointer.pointee.metadata) ?? "" }
        nonmutating set { lkSetString(&_pointer.pointee.metadata, newValue) }
    }

    var rid: UInt32 {
        get { _pointer.pointee.rid?.pointee ?? 0 }
        nonmutating set { lkSetValue(&_pointer.pointee.rid, newValue) }
    }

}

struct Livekit_MetricLabel: NanopbEnum {
    let rawValue: Int
    init(rawValue: Int) { self.rawValue = rawValue }
    init() { self.init(rawValue: 0) }

    static let agentsLlmTtft = Self(rawValue: 0)
    static let agentsSttTtft = Self(rawValue: 1)
    static let agentsTtsTtfb = Self(rawValue: 2)
    static let clientVideoSubscriberFreezeCount = Self(rawValue: 3)
    static let clientVideoSubscriberTotalFreezeDuration = Self(rawValue: 4)
    static let clientVideoSubscriberPauseCount = Self(rawValue: 5)
    static let clientVideoSubscriberTotalPausesDuration = Self(rawValue: 6)
    static let clientAudioSubscriberConcealedSamples = Self(rawValue: 7)
    static let clientAudioSubscriberSilentConcealedSamples = Self(rawValue: 8)
    static let clientAudioSubscriberConcealmentEvents = Self(rawValue: 9)
    static let clientAudioSubscriberInterruptionCount = Self(rawValue: 10)
    static let clientAudioSubscriberTotalInterruptionDuration = Self(rawValue: 11)
    static let clientSubscriberJitterBufferDelay = Self(rawValue: 12)
    static let clientSubscriberJitterBufferEmittedCount = Self(rawValue: 13)
    static let clientVideoPublisherQualityLimitationDurationBandwidth = Self(rawValue: 14)
    static let clientVideoPublisherQualityLimitationDurationCpu = Self(rawValue: 15)
    static let clientVideoPublisherQualityLimitationDurationOther = Self(rawValue: 16)
    static let publisherRtt = Self(rawValue: 17)
    static let serverMeshRtt = Self(rawValue: 18)
    static let subscriberRtt = Self(rawValue: 19)
    static let predefinedMaxValue = Self(rawValue: 4096)
}

