// Generated by scripts/generate-swift-protos.swift — do not edit.
//
// Immutable value facades over nanopb's C structs. Every message is the
// one generic NanopbMsg<Storage> — this file adds only a storage
// conformance, a typealias and the field accessors, so the schema
// contributes no Swift types of its own. Mutation goes through the
// noncopyable Builder. See Sources/LiveKitNanopb.

import Foundation

// Single-module builds compile these sources into the product directly:
// CocoaPods surfaces the C declarations through the umbrella header, while
// the prebuilt xcframework resolves CLiveKitProto via its modulemap — the
// internal import keeps it out of the emitted .swiftinterface.
#if LK_XCFRAMEWORK
package import CLiveKitProto
#elseif !COCOAPODS
import CLiveKitProto
import LiveKitNanopb
#endif

extension google_protobuf_Timestamp: NanopbStorage {
    package static var descriptor: pb_msgdesc_t { google_protobuf_Timestamp_msg }
    package static let _emptyBox = NanopbBox<google_protobuf_Timestamp>(zero: google_protobuf_Timestamp(), descriptor: google_protobuf_Timestamp_msg)
}
typealias Google_Protobuf_Timestamp = NanopbMsg<google_protobuf_Timestamp>
extension Google_Protobuf_Timestamp {
    var seconds: Int64 {
        _pointer.pointee.seconds?.pointee ?? 0
    }
    var hasSeconds: Bool { _pointer.pointee.seconds != nil }

    var nanos: Int32 {
        _pointer.pointee.nanos?.pointee ?? 0
    }
    var hasNanos: Bool { _pointer.pointee.nanos != nil }

}

extension Google_Protobuf_Timestamp.Builder {
    var seconds: Int64 {
        get { _pointer.pointee.seconds?.pointee ?? 0 }
        nonmutating set { lkSetValue(&_pointer.pointee.seconds, newValue) }
    }

    var nanos: Int32 {
        get { _pointer.pointee.nanos?.pointee ?? 0 }
        nonmutating set { lkSetValue(&_pointer.pointee.nanos, newValue) }
    }

}

