// Generated by scripts/generate-swift-protos.swift — do not edit.
//
// Immutable value facades over nanopb's C structs; mutation goes through
// each message's noncopyable Builder. See Sources/LiveKitNanopb.

import Foundation

// Single-module builds compile these sources into the product directly:
// CocoaPods surfaces the C declarations through the umbrella header, while
// the prebuilt xcframework resolves CLiveKitProto via its modulemap — the
// internal import keeps it out of the emitted .swiftinterface.
#if LK_XCFRAMEWORK
internal import CLiveKitProto
#elseif !COCOAPODS
import CLiveKitProto
import LiveKitNanopb
#endif

struct Google_Protobuf_Timestamp: NanopbMessage, @unchecked Sendable {
    typealias Storage = google_protobuf_Timestamp
    static var descriptor: pb_msgdesc_t { google_protobuf_Timestamp_msg }
    static var zero: Storage { Storage() }
    /// Shared value returned when a submessage field is absent. Safe to
    /// share because messages are immutable; `modifying` sees the static
    /// reference, so it copies rather than writing through it.
    static let _empty = Google_Protobuf_Timestamp()

    var _owner: NanopbAnyBox
    var _pointer: UnsafeMutablePointer<Storage>

    init() {
        self.init(_owning: NanopbBox(zero: Self.zero, descriptor: Self.descriptor))
    }

    init(_owning box: NanopbBox<Storage>) {
        _owner = box
        _pointer = box.pointer
    }

    /// Zero-copy view into `owner`'s storage.
    init(_sharing pointer: UnsafeMutablePointer<Storage>, owner: NanopbAnyBox) {
        _owner = owner
        _pointer = pointer
    }

    var seconds: Int64 {
        _pointer.pointee.seconds?.pointee ?? 0
    }
    var hasSeconds: Bool { _pointer.pointee.seconds != nil }

    var nanos: Int32 {
        _pointer.pointee.nanos?.pointee ?? 0
    }
    var hasNanos: Bool { _pointer.pointee.nanos != nil }

}

extension NanopbBuilder where M == Google_Protobuf_Timestamp {
    var seconds: Int64 {
        get { _pointer.pointee.seconds?.pointee ?? 0 }
        nonmutating set { lkSetValue(&_pointer.pointee.seconds, newValue) }
    }

    var nanos: Int32 {
        get { _pointer.pointee.nanos?.pointee ?? 0 }
        nonmutating set { lkSetValue(&_pointer.pointee.nanos, newValue) }
    }

}

