/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LIVEKIT_LIVEKIT_METRICS_PB_H_INCLUDED
#define PB_LIVEKIT_LIVEKIT_METRICS_PB_H_INCLUDED
#include <pb.h>
#include "timestamp.pb.h"
#include "options.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* index from [0: MAX_LABEL_PREDEFINED_MAX_VALUE) are for predefined labels (`MetricLabel`) */
typedef enum _livekit_MetricLabel {
    livekit_MetricLabel_AGENTS_LLM_TTFT = 0, /* time to first token from LLM */
    livekit_MetricLabel_AGENTS_STT_TTFT = 1, /* time to final transcription */
    livekit_MetricLabel_AGENTS_TTS_TTFB = 2, /* time to first byte */
    livekit_MetricLabel_CLIENT_VIDEO_SUBSCRIBER_FREEZE_COUNT = 3, /* Number of video freezes */
    livekit_MetricLabel_CLIENT_VIDEO_SUBSCRIBER_TOTAL_FREEZE_DURATION = 4, /* total duration of freezes */
    livekit_MetricLabel_CLIENT_VIDEO_SUBSCRIBER_PAUSE_COUNT = 5, /* number of video pauses */
    livekit_MetricLabel_CLIENT_VIDEO_SUBSCRIBER_TOTAL_PAUSES_DURATION = 6, /* total duration of pauses */
    livekit_MetricLabel_CLIENT_AUDIO_SUBSCRIBER_CONCEALED_SAMPLES = 7, /* number of concealed (synthesized) audio samples */
    livekit_MetricLabel_CLIENT_AUDIO_SUBSCRIBER_SILENT_CONCEALED_SAMPLES = 8, /* number of silent concealed samples */
    livekit_MetricLabel_CLIENT_AUDIO_SUBSCRIBER_CONCEALMENT_EVENTS = 9, /* number of concealment events */
    livekit_MetricLabel_CLIENT_AUDIO_SUBSCRIBER_INTERRUPTION_COUNT = 10, /* number of interruptions */
    livekit_MetricLabel_CLIENT_AUDIO_SUBSCRIBER_TOTAL_INTERRUPTION_DURATION = 11, /* total duration of interruptions */
    livekit_MetricLabel_CLIENT_SUBSCRIBER_JITTER_BUFFER_DELAY = 12, /* total time spent in jitter buffer */
    livekit_MetricLabel_CLIENT_SUBSCRIBER_JITTER_BUFFER_EMITTED_COUNT = 13, /* total time spent in jitter buffer */
    livekit_MetricLabel_CLIENT_VIDEO_PUBLISHER_QUALITY_LIMITATION_DURATION_BANDWIDTH = 14, /* total duration spent in bandwidth quality limitation */
    livekit_MetricLabel_CLIENT_VIDEO_PUBLISHER_QUALITY_LIMITATION_DURATION_CPU = 15, /* total duration spent in cpu quality limitation */
    livekit_MetricLabel_CLIENT_VIDEO_PUBLISHER_QUALITY_LIMITATION_DURATION_OTHER = 16, /* total duration spent in other quality limitation */
    livekit_MetricLabel_PUBLISHER_RTT = 17, /* Publisher RTT (participant -> server) */
    livekit_MetricLabel_SERVER_MESH_RTT = 18, /* RTT between publisher node and subscriber node (could involve intermedia node(s)) */
    livekit_MetricLabel_SUBSCRIBER_RTT = 19, /* Subscribe RTT (server -> participant) */
    livekit_MetricLabel_METRIC_LABEL_PREDEFINED_MAX_VALUE = 4096
} livekit_MetricLabel;

/* Struct definitions */
typedef struct _livekit_MetricsBatch {
    int64_t *timestamp_ms; /* time at which this batch is sent based on a monotonic clock (millisecond resolution) */
    struct _google_protobuf_Timestamp *normalized_timestamp;
    /* To avoid repeating string values, we store them in a separate list and reference them by index
 This is useful for storing participant identities, track names, etc.
 There is also a predefined list of labels that can be used to reference common metrics.
 They have reserved indices from 0 to (METRIC_LABEL_PREDEFINED_MAX_VALUE - 1).
 Indexes pointing at str_data should start from METRIC_LABEL_PREDEFINED_MAX_VALUE,
 such that str_data[0] == index of METRIC_LABEL_PREDEFINED_MAX_VALUE. */
    pb_size_t str_data_count;
    char **str_data;
    pb_size_t time_series_count;
    struct _livekit_TimeSeriesMetric *time_series;
    pb_size_t events_count;
    struct _livekit_EventMetric *events;
} livekit_MetricsBatch;

typedef struct _livekit_TimeSeriesMetric {
    /* Metric name e.g "speech_probablity". The string value is not directly stored in the message, but referenced by index
 in the `str_data` field of `MetricsBatch` */
    uint32_t *label;
    uint32_t *participant_identity; /* index into `str_data` */
    uint32_t *track_sid; /* index into `str_data` */
    pb_size_t samples_count;
    struct _livekit_MetricSample *samples;
    uint32_t *rid; /* index into 'str_data' */
} livekit_TimeSeriesMetric;

typedef struct _livekit_MetricSample {
    int64_t *timestamp_ms; /* time of metric based on a monotonic clock (in milliseconds) */
    struct _google_protobuf_Timestamp *normalized_timestamp;
    float *value;
} livekit_MetricSample;

typedef struct _livekit_EventMetric {
    uint32_t *label;
    uint32_t *participant_identity; /* index into `str_data` */
    uint32_t *track_sid; /* index into `str_data` */
    int64_t *start_timestamp_ms; /* start time of event based on a monotonic clock (in milliseconds) */
    int64_t *end_timestamp_ms; /* end time of event based on a monotonic clock (in milliseconds), if needed */
    struct _google_protobuf_Timestamp *normalized_start_timestamp;
    struct _google_protobuf_Timestamp *normalized_end_timestamp;
    char *metadata;
    uint32_t *rid; /* index into 'str_data' */
} livekit_EventMetric;

typedef struct _livekit_MetricsRecordingHeader {
    char *room_id;
    uint64_t *duration; /* milliseconds */
    struct _google_protobuf_Timestamp *start_time;
    pb_size_t room_tags_count;
    struct _livekit_MetricsRecordingHeader_RoomTagsEntry *room_tags;
    char *room_name;
    struct _google_protobuf_Timestamp *room_start_time;
    char *job_id;
    bool *simulated; /* session is a simulation; the collector skips PII redaction for it unless redaction_enabled is set */
    bool *redaction_enabled; /* force PII redaction on for this session (only ever enables, never disables) */
} livekit_MetricsRecordingHeader;

typedef struct _livekit_MetricsRecordingHeader_RoomTagsEntry {
    char *key;
    char *value;
} livekit_MetricsRecordingHeader_RoomTagsEntry;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _livekit_MetricLabel_MIN livekit_MetricLabel_AGENTS_LLM_TTFT
#define _livekit_MetricLabel_MAX livekit_MetricLabel_METRIC_LABEL_PREDEFINED_MAX_VALUE
#define _livekit_MetricLabel_ARRAYSIZE ((livekit_MetricLabel)(livekit_MetricLabel_METRIC_LABEL_PREDEFINED_MAX_VALUE+1))








/* Initializer values for message structs */
#define livekit_MetricsBatch_init_default        {NULL, NULL, 0, NULL, 0, NULL, 0, NULL}
#define livekit_TimeSeriesMetric_init_default    {NULL, NULL, NULL, 0, NULL, NULL}
#define livekit_MetricSample_init_default        {NULL, NULL, NULL}
#define livekit_EventMetric_init_default         {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL}
#define livekit_MetricsRecordingHeader_init_default {NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL}
#define livekit_MetricsRecordingHeader_RoomTagsEntry_init_default {NULL, NULL}
#define livekit_MetricsBatch_init_zero           {NULL, NULL, 0, NULL, 0, NULL, 0, NULL}
#define livekit_TimeSeriesMetric_init_zero       {NULL, NULL, NULL, 0, NULL, NULL}
#define livekit_MetricSample_init_zero           {NULL, NULL, NULL}
#define livekit_EventMetric_init_zero            {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL}
#define livekit_MetricsRecordingHeader_init_zero {NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL}
#define livekit_MetricsRecordingHeader_RoomTagsEntry_init_zero {NULL, NULL}

/* Field tags (for use in manual encoding/decoding) */
#define livekit_MetricsBatch_timestamp_ms_tag    1
#define livekit_MetricsBatch_normalized_timestamp_tag 2
#define livekit_MetricsBatch_str_data_tag        3
#define livekit_MetricsBatch_time_series_tag     4
#define livekit_MetricsBatch_events_tag          5
#define livekit_TimeSeriesMetric_label_tag       1
#define livekit_TimeSeriesMetric_participant_identity_tag 2
#define livekit_TimeSeriesMetric_track_sid_tag   3
#define livekit_TimeSeriesMetric_samples_tag     4
#define livekit_TimeSeriesMetric_rid_tag         5
#define livekit_MetricSample_timestamp_ms_tag    1
#define livekit_MetricSample_normalized_timestamp_tag 2
#define livekit_MetricSample_value_tag           3
#define livekit_EventMetric_label_tag            1
#define livekit_EventMetric_participant_identity_tag 2
#define livekit_EventMetric_track_sid_tag        3
#define livekit_EventMetric_start_timestamp_ms_tag 4
#define livekit_EventMetric_end_timestamp_ms_tag 5
#define livekit_EventMetric_normalized_start_timestamp_tag 6
#define livekit_EventMetric_normalized_end_timestamp_tag 7
#define livekit_EventMetric_metadata_tag         8
#define livekit_EventMetric_rid_tag              9
#define livekit_MetricsRecordingHeader_room_id_tag 1
#define livekit_MetricsRecordingHeader_duration_tag 3
#define livekit_MetricsRecordingHeader_start_time_tag 4
#define livekit_MetricsRecordingHeader_room_tags_tag 5
#define livekit_MetricsRecordingHeader_room_name_tag 6
#define livekit_MetricsRecordingHeader_room_start_time_tag 7
#define livekit_MetricsRecordingHeader_job_id_tag 8
#define livekit_MetricsRecordingHeader_simulated_tag 9
#define livekit_MetricsRecordingHeader_redaction_enabled_tag 10
#define livekit_MetricsRecordingHeader_RoomTagsEntry_key_tag 1
#define livekit_MetricsRecordingHeader_RoomTagsEntry_value_tag 2

/* Struct field encoding specification for nanopb */
#define livekit_MetricsBatch_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, INT64,    timestamp_ms,      1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  normalized_timestamp,   2) \
X(a, POINTER,  REPEATED, STRING,   str_data,          3) \
X(a, POINTER,  REPEATED, MESSAGE,  time_series,       4) \
X(a, POINTER,  REPEATED, MESSAGE,  events,            5)
#define livekit_MetricsBatch_CALLBACK NULL
#define livekit_MetricsBatch_DEFAULT NULL
#define livekit_MetricsBatch_normalized_timestamp_MSGTYPE google_protobuf_Timestamp
#define livekit_MetricsBatch_time_series_MSGTYPE livekit_TimeSeriesMetric
#define livekit_MetricsBatch_events_MSGTYPE livekit_EventMetric

#define livekit_TimeSeriesMetric_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, UINT32,   label,             1) \
X(a, POINTER,  SINGULAR, UINT32,   participant_identity,   2) \
X(a, POINTER,  SINGULAR, UINT32,   track_sid,         3) \
X(a, POINTER,  REPEATED, MESSAGE,  samples,           4) \
X(a, POINTER,  SINGULAR, UINT32,   rid,               5)
#define livekit_TimeSeriesMetric_CALLBACK NULL
#define livekit_TimeSeriesMetric_DEFAULT NULL
#define livekit_TimeSeriesMetric_samples_MSGTYPE livekit_MetricSample

#define livekit_MetricSample_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, INT64,    timestamp_ms,      1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  normalized_timestamp,   2) \
X(a, POINTER,  SINGULAR, FLOAT,    value,             3)
#define livekit_MetricSample_CALLBACK NULL
#define livekit_MetricSample_DEFAULT NULL
#define livekit_MetricSample_normalized_timestamp_MSGTYPE google_protobuf_Timestamp

#define livekit_EventMetric_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, UINT32,   label,             1) \
X(a, POINTER,  SINGULAR, UINT32,   participant_identity,   2) \
X(a, POINTER,  SINGULAR, UINT32,   track_sid,         3) \
X(a, POINTER,  SINGULAR, INT64,    start_timestamp_ms,   4) \
X(a, POINTER,  OPTIONAL, INT64,    end_timestamp_ms,   5) \
X(a, POINTER,  OPTIONAL, MESSAGE,  normalized_start_timestamp,   6) \
X(a, POINTER,  OPTIONAL, MESSAGE,  normalized_end_timestamp,   7) \
X(a, POINTER,  SINGULAR, STRING,   metadata,          8) \
X(a, POINTER,  SINGULAR, UINT32,   rid,               9)
#define livekit_EventMetric_CALLBACK NULL
#define livekit_EventMetric_DEFAULT NULL
#define livekit_EventMetric_normalized_start_timestamp_MSGTYPE google_protobuf_Timestamp
#define livekit_EventMetric_normalized_end_timestamp_MSGTYPE google_protobuf_Timestamp

#define livekit_MetricsRecordingHeader_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   room_id,           1) \
X(a, POINTER,  SINGULAR, UINT64,   duration,          3) \
X(a, POINTER,  OPTIONAL, MESSAGE,  start_time,        4) \
X(a, POINTER,  REPEATED, MESSAGE,  room_tags,         5) \
X(a, POINTER,  SINGULAR, STRING,   room_name,         6) \
X(a, POINTER,  OPTIONAL, MESSAGE,  room_start_time,   7) \
X(a, POINTER,  SINGULAR, STRING,   job_id,            8) \
X(a, POINTER,  SINGULAR, BOOL,     simulated,         9) \
X(a, POINTER,  SINGULAR, BOOL,     redaction_enabled,  10)
#define livekit_MetricsRecordingHeader_CALLBACK NULL
#define livekit_MetricsRecordingHeader_DEFAULT NULL
#define livekit_MetricsRecordingHeader_start_time_MSGTYPE google_protobuf_Timestamp
#define livekit_MetricsRecordingHeader_room_tags_MSGTYPE livekit_MetricsRecordingHeader_RoomTagsEntry
#define livekit_MetricsRecordingHeader_room_start_time_MSGTYPE google_protobuf_Timestamp

#define livekit_MetricsRecordingHeader_RoomTagsEntry_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   key,               1) \
X(a, POINTER,  SINGULAR, STRING,   value,             2)
#define livekit_MetricsRecordingHeader_RoomTagsEntry_CALLBACK NULL
#define livekit_MetricsRecordingHeader_RoomTagsEntry_DEFAULT NULL

extern const pb_msgdesc_t livekit_MetricsBatch_msg;
extern const pb_msgdesc_t livekit_TimeSeriesMetric_msg;
extern const pb_msgdesc_t livekit_MetricSample_msg;
extern const pb_msgdesc_t livekit_EventMetric_msg;
extern const pb_msgdesc_t livekit_MetricsRecordingHeader_msg;
extern const pb_msgdesc_t livekit_MetricsRecordingHeader_RoomTagsEntry_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define livekit_MetricsBatch_fields &livekit_MetricsBatch_msg
#define livekit_TimeSeriesMetric_fields &livekit_TimeSeriesMetric_msg
#define livekit_MetricSample_fields &livekit_MetricSample_msg
#define livekit_EventMetric_fields &livekit_EventMetric_msg
#define livekit_MetricsRecordingHeader_fields &livekit_MetricsRecordingHeader_msg
#define livekit_MetricsRecordingHeader_RoomTagsEntry_fields &livekit_MetricsRecordingHeader_RoomTagsEntry_msg

/* Maximum encoded size of messages (where known) */
/* livekit_MetricsBatch_size depends on runtime parameters */
/* livekit_TimeSeriesMetric_size depends on runtime parameters */
/* livekit_MetricSample_size depends on runtime parameters */
/* livekit_EventMetric_size depends on runtime parameters */
/* livekit_MetricsRecordingHeader_size depends on runtime parameters */
/* livekit_MetricsRecordingHeader_RoomTagsEntry_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
