name: Benchmarks

permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  benchmark:
    name: Benchmark
    runs-on: macos-latest
    timeout-minutes: 60
    env:
      LK_BENCHMARK: 1
      # LIVEKIT_URL: ${{ secrets.BENCHMARK_URL }}
      # LIVEKIT_API_KEY: ${{ secrets.BENCHMARK_API_KEY }}
      # LIVEKIT_API_SECRET: ${{ secrets.BENCHMARK_API_SECRET }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install livekit jemalloc swiftly && swiftly init --quiet-shell-followup --skip-install -y

      - name: Run LiveKit Server
        run: livekit-server --dev &

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Run Benchmarks
        working-directory: Benchmarks
        run: |
          swiftly run +xcode swift package --disable-sandbox \
            benchmark baseline update current

      - name: Benchmark Report
        working-directory: Benchmarks
        run: |
          swiftly run +xcode swift package --disable-sandbox \
            benchmark baseline read current \
            --format markdown \
            | tee -a "$GITHUB_STEP_SUMMARY"
