name: Benchmarks

permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  benchmark:
    name: Benchmark
    runs-on: macos-latest
    timeout-minutes: 60
    env:
      LK_BENCHMARK: 1
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install livekit jemalloc swiftly

      - name: Run LiveKit Server
        run: livekit-server --dev &

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Run Benchmarks
        working-directory: Benchmarks
        run: swiftly run +xcode swift package --disable-sandbox benchmark thresholds check
