name: CocoaPods Push
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: Dry run (only lint spec, don't push)
        default: true
        type: boolean
  release:
    types: [published]
env:
  PODSPEC_FILE: LiveKitClient.podspec
jobs:
  push:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup CocoaPods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: latest
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Add Repo
        run: |
          pod repo add livekit https://github.com/livekit/podspecs.git
      - name: Spec Lint
        id: spec-lint
        run: |
          validation_dir=$(mktemp -d)
          echo "validation_dir=${validation_dir}" >> $GITHUB_OUTPUT
          pod spec lint \
            --platforms=macos \
            --validation-dir="${validation_dir}" \
            --no-clean \
            --allow-warnings \
            --verbose \
            --sources=livekit,https://cdn.cocoapods.org/
      - name: Upload Validation Directory (Failure Only)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.spec-lint.outputs.validation_dir }}
          name: validation
      - name: Push to CocoaPods
        if: ${{ inputs.dry_run != true && success() }}
        run: |
          pod trunk push ${{ env.PODSPEC_FILE }} \
            --allow-warnings \
            --verbose \
            --sources=livekit,https://cdn.cocoapods.org/
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
