name: Swift Snapshot Build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/swift-snapshot.yaml'

jobs:
  build-snapshot:
    name: Build
    runs-on: macos-latest
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Install swiftly
        run: brew install swiftly && swiftly init --quiet-shell-followup --skip-install -y

      - name: Use Swift Snapshot
        run:  swiftly install -y main-snapshot && swiftly use -y main-snapshot

      - name: Build
        run: swift build
